#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'AccountApi' {
    Context 'Get-AccountLimits' {
        It 'Test Get-AccountLimits' {
            #$TestResult = Get-AccountLimits
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
