#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DNSServersApi' {
    Context 'New-DNSServer' {
        It 'Test New-DNSServer' {
            #$TestResult = New-DNSServer -DNSServerCreate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-DNSServer' {
        It 'Test Get-DNSServer' {
            #$TestResult = Get-DNSServer -DnsServerId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Invoke-ListDNSServers' {
        It 'Test Invoke-ListDNSServers' {
            #$TestResult = Invoke-ListDNSServers
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Remove-DNSServer' {
        It 'Test Remove-DNSServer' {
            #$TestResult = Remove-DNSServer -DnsServerId "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-DNSServer' {
        It 'Test Update-DNSServer' {
            #$TestResult = Update-DNSServer -DnsServerId "TEST_VALUE" -DNSServerUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Update-DNSServerSettings' {
        It 'Test Update-DNSServerSettings' {
            #$TestResult = Update-DNSServerSettings -DnsServerId "TEST_VALUE" -DNSServerSettingsUpdate "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
