#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'StatisticsApi' {
    Context 'Get-CategoriesQueriesStats' {
        It 'Test Get-CategoriesQueriesStats' {
            #$TestResult = Get-CategoriesQueriesStats -TimeFromMillis "TEST_VALUE" -TimeToMillis "TEST_VALUE" -Devices "TEST_VALUE" -Countries "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-CompaniesStats' {
        It 'Test Get-CompaniesStats' {
            #$TestResult = Get-CompaniesStats -TimeFromMillis "TEST_VALUE" -TimeToMillis "TEST_VALUE" -Devices "TEST_VALUE" -Countries "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-CountriesQueriesStats' {
        It 'Test Get-CountriesQueriesStats' {
            #$TestResult = Get-CountriesQueriesStats -TimeFromMillis "TEST_VALUE" -TimeToMillis "TEST_VALUE" -Devices "TEST_VALUE" -Countries "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-DetailedCompaniesStats' {
        It 'Test Get-DetailedCompaniesStats' {
            #$TestResult = Get-DetailedCompaniesStats -TimeFromMillis "TEST_VALUE" -TimeToMillis "TEST_VALUE" -Devices "TEST_VALUE" -Countries "TEST_VALUE" -Cursor "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-DevicesQueriesStats' {
        It 'Test Get-DevicesQueriesStats' {
            #$TestResult = Get-DevicesQueriesStats -TimeFromMillis "TEST_VALUE" -TimeToMillis "TEST_VALUE" -Devices "TEST_VALUE" -Countries "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-DomainsQueriesStats' {
        It 'Test Get-DomainsQueriesStats' {
            #$TestResult = Get-DomainsQueriesStats -TimeFromMillis "TEST_VALUE" -TimeToMillis "TEST_VALUE" -Devices "TEST_VALUE" -Countries "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

    Context 'Get-TimeQueriesStats' {
        It 'Test Get-TimeQueriesStats' {
            #$TestResult = Get-TimeQueriesStats -TimeFromMillis "TEST_VALUE" -TimeToMillis "TEST_VALUE" -Devices "TEST_VALUE" -Countries "TEST_VALUE"
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
