#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'WebServicesApi' {
    Context 'Invoke-ListWebServices' {
        It 'Test Invoke-ListWebServices' {
            #$TestResult = Invoke-ListWebServices
            #$TestResult | Should -BeOfType TODO
            #$TestResult.property | Should -Be 0
        }
    }

}
