/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace AdGuard.ApiClient.Api;

/// <summary>
/// Represents a collection of functions to interact with the API endpoints
/// </summary>
public partial class DedicatedIPAddressesApi : IDisposable, IDedicatedIPAddressesApi
{
    private AdGuard.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

    /// <summary>
    /// Initializes a new instance of the <see cref="DedicatedIPAddressesApi"/> class.
    /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
    /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
    /// </summary>
    /// <returns></returns>
    public DedicatedIPAddressesApi() : this((string)null)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DedicatedIPAddressesApi"/> class.
    /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
    /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
    /// </summary>
    /// <param name="basePath">The target service's base path in URL format.</param>
    /// <exception cref="ArgumentException"></exception>
    /// <returns></returns>
    public DedicatedIPAddressesApi(string basePath)
    {
        this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
            AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
            new AdGuard.ApiClient.Client.Configuration { BasePath = basePath }
        );
        this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(this.Configuration.BasePath);
        this.Client = this.ApiClient;
        this.AsynchronousClient = this.ApiClient;
        this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DedicatedIPAddressesApi"/> class using Configuration object.
    /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
    /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
    /// </summary>
    /// <param name="configuration">An instance of Configuration.</param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <returns></returns>
    public DedicatedIPAddressesApi(AdGuard.ApiClient.Client.Configuration configuration)
    {
        if (configuration == null) throw new ArgumentNullException("configuration");

        this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
            AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
            configuration
        );
        this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(this.Configuration.BasePath);
        this.Client = this.ApiClient;
        this.AsynchronousClient = this.ApiClient;
        ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DedicatedIPAddressesApi"/> class.
    /// </summary>
    /// <param name="client">An instance of HttpClient.</param>
    /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <returns></returns>
    /// <remarks>
    /// Some configuration settings will not be applied without passing an HttpClientHandler.
    /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
    /// </remarks>
    public DedicatedIPAddressesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
    {
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DedicatedIPAddressesApi"/> class.
    /// </summary>
    /// <param name="client">An instance of HttpClient.</param>
    /// <param name="basePath">The target service's base path in URL format.</param>
    /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="ArgumentException"></exception>
    /// <returns></returns>
    /// <remarks>
    /// Some configuration settings will not be applied without passing an HttpClientHandler.
    /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
    /// </remarks>
    public DedicatedIPAddressesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
    {
        if (client == null) throw new ArgumentNullException("client");

        this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
            AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
            new AdGuard.ApiClient.Client.Configuration { BasePath = basePath }
        );
        this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
        this.Client = this.ApiClient;
        this.AsynchronousClient = this.ApiClient;
        this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DedicatedIPAddressesApi"/> class using Configuration object.
    /// </summary>
    /// <param name="client">An instance of HttpClient.</param>
    /// <param name="configuration">An instance of Configuration.</param>
    /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
    /// <exception cref="ArgumentNullException"></exception>
    /// <returns></returns>
    /// <remarks>
    /// Some configuration settings will not be applied without passing an HttpClientHandler.
    /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
    /// </remarks>
    public DedicatedIPAddressesApi(HttpClient client, AdGuard.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
    {
        if (configuration == null) throw new ArgumentNullException("configuration");
        if (client == null) throw new ArgumentNullException("client");

        this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
            AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
            configuration
        );
        this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
        this.Client = this.ApiClient;
        this.AsynchronousClient = this.ApiClient;
        ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="DedicatedIPAddressesApi"/> class
    /// using a Configuration object and client instance.
    /// </summary>
    /// <param name="client">The client interface for synchronous API access.</param>
    /// <param name="asyncClient">The client interface for asynchronous API access.</param>
    /// <param name="configuration">The configuration object.</param>
    /// <exception cref="ArgumentNullException"></exception>
    public DedicatedIPAddressesApi(AdGuard.ApiClient.Client.ISynchronousClient client, AdGuard.ApiClient.Client.IAsynchronousClient asyncClient, AdGuard.ApiClient.Client.IReadableConfiguration configuration)
    {
        if (client == null) throw new ArgumentNullException("client");
        if (asyncClient == null) throw new ArgumentNullException("asyncClient");
        if (configuration == null) throw new ArgumentNullException("configuration");

        this.Client = client;
        this.AsynchronousClient = asyncClient;
        this.Configuration = configuration;
        this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    /// Disposes resources if they were created by us
    /// </summary>
    public void Dispose()
    {
        this.ApiClient?.Dispose();
    }

    /// <summary>
    /// Holds the ApiClient if created
    /// </summary>
    public AdGuard.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

    /// <summary>
    /// The client for accessing this underlying API asynchronously.
    /// </summary>
    public AdGuard.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

    /// <summary>
    /// The client for accessing this underlying API synchronously.
    /// </summary>
    public AdGuard.ApiClient.Client.ISynchronousClient Client { get; set; }

    /// <summary>
    /// Gets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    public string GetBasePath()
    {
        return this.Configuration.BasePath;
    }

    /// <summary>
    /// Gets or sets the configuration object
    /// </summary>
    /// <value>An instance of the Configuration</value>
    public AdGuard.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

    /// <summary>
    /// Provides a factory method hook for the creation of exceptions.
    /// </summary>
    public AdGuard.ApiClient.Client.ExceptionFactory ExceptionFactory
    {
        get
        {
            if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
            {
                throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
            }
            return _exceptionFactory;
        }
        set { _exceptionFactory = value; }
    }

    /// <summary>
    /// Allocates new dedicated IPv4 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <returns>DedicatedIPv4Address</returns>
    public DedicatedIPv4Address AllocateDedicatedIPv4Address()
    {
        AdGuard.ApiClient.Client.ApiResponse<DedicatedIPv4Address> localVarResponse = AllocateDedicatedIPv4AddressWithHttpInfo();
        return localVarResponse.Data;
    }

    /// <summary>
    /// Allocates new dedicated IPv4 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <returns>ApiResponse of DedicatedIPv4Address</returns>
    public AdGuard.ApiClient.Client.ApiResponse<DedicatedIPv4Address> AllocateDedicatedIPv4AddressWithHttpInfo()
    {
        AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

        string[] _contentTypes = new string[] {
        };

        // to determine the Accept header
        string[] _accepts = new string[] {
            "*/*"
        };

        var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

        var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


        // authentication (ApiKey) required
        if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
        }
        // authentication (AuthToken) required
        // bearer authentication required
        if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
        }

        // make the HTTP request
        var localVarResponse = this.Client.Post<DedicatedIPv4Address>("/oapi/v1/dedicated_addresses/ipv4", localVarRequestOptions, this.Configuration);

        if (this.ExceptionFactory != null)
        {
            Exception _exception = this.ExceptionFactory("AllocateDedicatedIPv4Address", localVarResponse);
            if (_exception != null) throw _exception;
        }

        return localVarResponse;
    }

    /// <summary>
    /// Allocates new dedicated IPv4 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of DedicatedIPv4Address</returns>
    public async System.Threading.Tasks.Task<DedicatedIPv4Address> AllocateDedicatedIPv4AddressAsync(System.Threading.CancellationToken cancellationToken = default)
    {
        AdGuard.ApiClient.Client.ApiResponse<DedicatedIPv4Address> localVarResponse = await AllocateDedicatedIPv4AddressWithHttpInfoAsync(cancellationToken);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Allocates new dedicated IPv4 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (DedicatedIPv4Address)</returns>
    public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<DedicatedIPv4Address>> AllocateDedicatedIPv4AddressWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
    {

        AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

        string[] _contentTypes = new string[] {
        };

        // to determine the Accept header
        string[] _accepts = new string[] {
            "*/*"
        };


        var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

        var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


        // authentication (ApiKey) required
        if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
        }
        // authentication (AuthToken) required
        // bearer authentication required
        if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
        }

        // make the HTTP request

        var localVarResponse = await this.AsynchronousClient.PostAsync<DedicatedIPv4Address>("/oapi/v1/dedicated_addresses/ipv4", localVarRequestOptions, this.Configuration, cancellationToken);

        if (this.ExceptionFactory != null)
        {
            Exception _exception = this.ExceptionFactory("AllocateDedicatedIPv4Address", localVarResponse);
            if (_exception != null) throw _exception;
        }

        return localVarResponse;
    }

    /// <summary>
    /// Lists allocated dedicated IPv4 addresses 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <returns>List&lt;DedicatedIPv4Address&gt;</returns>
    public List<DedicatedIPv4Address> ListDedicatedIPv4Addresses()
    {
        AdGuard.ApiClient.Client.ApiResponse<List<DedicatedIPv4Address>> localVarResponse = ListDedicatedIPv4AddressesWithHttpInfo();
        return localVarResponse.Data;
    }

    /// <summary>
    /// Lists allocated dedicated IPv4 addresses 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <returns>ApiResponse of List&lt;DedicatedIPv4Address&gt;</returns>
    public AdGuard.ApiClient.Client.ApiResponse<List<DedicatedIPv4Address>> ListDedicatedIPv4AddressesWithHttpInfo()
    {
        AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

        string[] _contentTypes = new string[] {
        };

        // to determine the Accept header
        string[] _accepts = new string[] {
            "*/*"
        };

        var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

        var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


        // authentication (ApiKey) required
        if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
        }
        // authentication (AuthToken) required
        // bearer authentication required
        if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
        }

        // make the HTTP request
        var localVarResponse = this.Client.Get<List<DedicatedIPv4Address>>("/oapi/v1/dedicated_addresses/ipv4", localVarRequestOptions, this.Configuration);

        if (this.ExceptionFactory != null)
        {
            Exception _exception = this.ExceptionFactory("ListDedicatedIPv4Addresses", localVarResponse);
            if (_exception != null) throw _exception;
        }

        return localVarResponse;
    }

    /// <summary>
    /// Lists allocated dedicated IPv4 addresses 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of List&lt;DedicatedIPv4Address&gt;</returns>
    public async System.Threading.Tasks.Task<List<DedicatedIPv4Address>> ListDedicatedIPv4AddressesAsync(System.Threading.CancellationToken cancellationToken = default)
    {
        AdGuard.ApiClient.Client.ApiResponse<List<DedicatedIPv4Address>> localVarResponse = await ListDedicatedIPv4AddressesWithHttpInfoAsync(cancellationToken);
        return localVarResponse.Data;
    }

    /// <summary>
    /// Lists allocated dedicated IPv4 addresses 
    /// </summary>
    /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
    /// <returns>Task of ApiResponse (List&lt;DedicatedIPv4Address&gt;)</returns>
    public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<List<DedicatedIPv4Address>>> ListDedicatedIPv4AddressesWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
    {

        AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

        string[] _contentTypes = new string[] {
        };

        // to determine the Accept header
        string[] _accepts = new string[] {
            "*/*"
        };


        var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
        if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

        var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
        if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


        // authentication (ApiKey) required
        if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
        }
        // authentication (AuthToken) required
        // bearer authentication required
        if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
        {
            localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
        }

        // make the HTTP request

        var localVarResponse = await this.AsynchronousClient.GetAsync<List<DedicatedIPv4Address>>("/oapi/v1/dedicated_addresses/ipv4", localVarRequestOptions, this.Configuration, cancellationToken);

        if (this.ExceptionFactory != null)
        {
            Exception _exception = this.ExceptionFactory("ListDedicatedIPv4Addresses", localVarResponse);
            if (_exception != null) throw _exception;
        }

        return localVarResponse;
    }

}