/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using AdGuard.ApiClient.Client;
using AdGuard.ApiClient.Api;
// uncomment below to import models
//using AdGuard.ApiClient.Model;

namespace AdGuard.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing DNSServersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DNSServersApiTests : IDisposable
    {
        private DNSServersApi instance;

        public DNSServersApiTests()
        {
            instance = new DNSServersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DNSServersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DNSServersApi
            //Assert.IsType<DNSServersApi>(instance);
        }

        /// <summary>
        /// Test CreateDNSServer
        /// </summary>
        [Fact]
        public void CreateDNSServerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DNSServerCreate dNSServerCreate = null;
            //var response = instance.CreateDNSServer(dNSServerCreate);
            //Assert.IsType<DNSServer>(response);
        }

        /// <summary>
        /// Test ListDNSServers
        /// </summary>
        [Fact]
        public void ListDNSServersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListDNSServers();
            //Assert.IsType<List<DNSServer>>(response);
        }
    }
}
