/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AdGuard.ApiClient.Model;
using AdGuard.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AdGuard.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing TimeQueriesStatsList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimeQueriesStatsListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimeQueriesStatsList
        //private TimeQueriesStatsList instance;

        public TimeQueriesStatsListTests()
        {
            // TODO uncomment below to create an instance of TimeQueriesStatsList
            //instance = new TimeQueriesStatsList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimeQueriesStatsList
        /// </summary>
        [Fact]
        public void TimeQueriesStatsListInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimeQueriesStatsList
            //Assert.IsType<TimeQueriesStatsList>(instance);
        }

        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
    }
}
