/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Account limits
    /// </summary>
    [DataContract(Name = "AccountLimits")]
    public partial class AccountLimits : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountLimits" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccountLimits() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountLimits" /> class.
        /// </summary>
        /// <param name="accessRules">accessRules (required).</param>
        /// <param name="dedicatedIpv4">dedicatedIpv4 (required).</param>
        /// <param name="devices">devices (required).</param>
        /// <param name="dnsServers">dnsServers (required).</param>
        /// <param name="requests">requests (required).</param>
        /// <param name="userRules">userRules (required).</param>
        public AccountLimits(Limit accessRules = default, Limit dedicatedIpv4 = default, Limit devices = default, Limit dnsServers = default, Limit requests = default, Limit userRules = default)
        {
            // to ensure "accessRules" is required (not null)
            if (accessRules == null)
            {
                throw new ArgumentNullException("accessRules is a required property for AccountLimits and cannot be null");
            }
            this.AccessRules = accessRules;
            // to ensure "dedicatedIpv4" is required (not null)
            if (dedicatedIpv4 == null)
            {
                throw new ArgumentNullException("dedicatedIpv4 is a required property for AccountLimits and cannot be null");
            }
            this.DedicatedIpv4 = dedicatedIpv4;
            // to ensure "devices" is required (not null)
            if (devices == null)
            {
                throw new ArgumentNullException("devices is a required property for AccountLimits and cannot be null");
            }
            this.Devices = devices;
            // to ensure "dnsServers" is required (not null)
            if (dnsServers == null)
            {
                throw new ArgumentNullException("dnsServers is a required property for AccountLimits and cannot be null");
            }
            this.DnsServers = dnsServers;
            // to ensure "requests" is required (not null)
            if (requests == null)
            {
                throw new ArgumentNullException("requests is a required property for AccountLimits and cannot be null");
            }
            this.Requests = requests;
            // to ensure "userRules" is required (not null)
            if (userRules == null)
            {
                throw new ArgumentNullException("userRules is a required property for AccountLimits and cannot be null");
            }
            this.UserRules = userRules;
        }

        /// <summary>
        /// Gets or Sets AccessRules
        /// </summary>
        [DataMember(Name = "access_rules", IsRequired = true, EmitDefaultValue = true)]
        public Limit AccessRules { get; set; }

        /// <summary>
        /// Gets or Sets DedicatedIpv4
        /// </summary>
        [DataMember(Name = "dedicated_ipv4", IsRequired = true, EmitDefaultValue = true)]
        public Limit DedicatedIpv4 { get; set; }

        /// <summary>
        /// Gets or Sets Devices
        /// </summary>
        [DataMember(Name = "devices", IsRequired = true, EmitDefaultValue = true)]
        public Limit Devices { get; set; }

        /// <summary>
        /// Gets or Sets DnsServers
        /// </summary>
        [DataMember(Name = "dns_servers", IsRequired = true, EmitDefaultValue = true)]
        public Limit DnsServers { get; set; }

        /// <summary>
        /// Gets or Sets Requests
        /// </summary>
        [DataMember(Name = "requests", IsRequired = true, EmitDefaultValue = true)]
        public Limit Requests { get; set; }

        /// <summary>
        /// Gets or Sets UserRules
        /// </summary>
        [DataMember(Name = "user_rules", IsRequired = true, EmitDefaultValue = true)]
        public Limit UserRules { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountLimits {\n");
            sb.Append("  AccessRules: ").Append(AccessRules).Append("\n");
            sb.Append("  DedicatedIpv4: ").Append(DedicatedIpv4).Append("\n");
            sb.Append("  Devices: ").Append(Devices).Append("\n");
            sb.Append("  DnsServers: ").Append(DnsServers).Append("\n");
            sb.Append("  Requests: ").Append(Requests).Append("\n");
            sb.Append("  UserRules: ").Append(UserRules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
