/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using AdGuard.ApiClient.Client;

namespace AdGuard.ApiClient.Helpers
{
    /// <summary>
    /// Helper class for configuring AdGuard DNS API client
    /// </summary>
    public static class ConfigurationHelper
    {
        private const string DefaultBasePath = "https://api.adguard-dns.io";

        /// <summary>
        /// Creates a configuration with API Key authentication
        /// </summary>
        /// <param name="apiKey">Your AdGuard DNS API key</param>
        /// <param name="basePath">Optional base path (defaults to https://api.adguard-dns.io)</param>
        /// <returns>Configured Configuration instance</returns>
        public static Configuration CreateWithApiKey(string apiKey, string? basePath = null)
        {
            if (string.IsNullOrWhiteSpace(apiKey))
                throw new ArgumentException("API key cannot be null or empty", nameof(apiKey));

            return new Configuration
            {
                BasePath = basePath ?? DefaultBasePath,
                ApiKey = new Dictionary<string, string>
                {
                    { "Authorization", $"ApiKey {apiKey}" }
                }
            };
        }

        /// <summary>
        /// Creates a configuration with Bearer token authentication
        /// </summary>
        /// <param name="accessToken">Your OAuth access token</param>
        /// <param name="basePath">Optional base path (defaults to https://api.adguard-dns.io)</param>
        /// <returns>Configured Configuration instance</returns>
        public static Configuration CreateWithBearerToken(string accessToken, string? basePath = null)
        {
            if (string.IsNullOrWhiteSpace(accessToken))
                throw new ArgumentException("Access token cannot be null or empty", nameof(accessToken));

            return new Configuration
            {
                BasePath = basePath ?? DefaultBasePath,
                AccessToken = accessToken
            };
        }

        /// <summary>
        /// Creates a configuration with custom settings
        /// </summary>
        /// <param name="basePath">API base path</param>
        /// <param name="timeout">Optional timeout in milliseconds</param>
        /// <param name="userAgent">Optional custom user agent</param>
        /// <returns>Configured Configuration instance</returns>
        public static Configuration CreateCustom(string? basePath = null, int? timeout = null, string? userAgent = null)
        {
            var config = new Configuration
            {
                BasePath = basePath ?? DefaultBasePath
            };

            if (timeout.HasValue)
                config.Timeout = timeout.Value;

            if (!string.IsNullOrWhiteSpace(userAgent))
                config.UserAgent = userAgent;

            return config;
        }

        /// <summary>
        /// Adds API Key authentication to an existing configuration
        /// </summary>
        /// <param name="configuration">Configuration to modify</param>
        /// <param name="apiKey">API key to add</param>
        /// <returns>The modified configuration for method chaining</returns>
        public static Configuration WithApiKey(this Configuration configuration, string apiKey)
        {
            if (string.IsNullOrWhiteSpace(apiKey))
                throw new ArgumentException("API key cannot be null or empty", nameof(apiKey));

            configuration.ApiKey ??= new Dictionary<string, string>();
            configuration.ApiKey["Authorization"] = $"ApiKey {apiKey}";

            return configuration;
        }

        /// <summary>
        /// Adds Bearer token authentication to an existing configuration
        /// </summary>
        /// <param name="configuration">Configuration to modify</param>
        /// <param name="accessToken">Access token to add</param>
        /// <returns>The modified configuration for method chaining</returns>
        public static Configuration WithBearerToken(this Configuration configuration, string accessToken)
        {
            if (string.IsNullOrWhiteSpace(accessToken))
                throw new ArgumentException("Access token cannot be null or empty", nameof(accessToken));

            configuration.AccessToken = accessToken;

            return configuration;
        }

        /// <summary>
        /// Sets the timeout for the configuration
        /// </summary>
        /// <param name="configuration">Configuration to modify</param>
        /// <param name="timeoutMilliseconds">Timeout in milliseconds</param>
        /// <returns>The modified configuration for method chaining</returns>
        public static Configuration WithTimeout(this Configuration configuration, int timeoutMilliseconds)
        {
            if (timeoutMilliseconds <= 0)
                throw new ArgumentException("Timeout must be greater than 0", nameof(timeoutMilliseconds));

            configuration.Timeout = timeoutMilliseconds;

            return configuration;
        }

        /// <summary>
        /// Sets a custom user agent for the configuration
        /// </summary>
        /// <param name="configuration">Configuration to modify</param>
        /// <param name="userAgent">User agent string</param>
        /// <returns>The modified configuration for method chaining</returns>
        public static Configuration WithUserAgent(this Configuration configuration, string userAgent)
        {
            if (string.IsNullOrWhiteSpace(userAgent))
                throw new ArgumentException("User agent cannot be null or empty", nameof(userAgent));

            configuration.UserAgent = userAgent;

            return configuration;
        }
    }
}
