/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using AdGuard.ApiClient.Client;
using AdGuard.ApiClient.Model;

namespace AdGuard.ApiClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDNSServersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Creates a new DNS server
        /// </summary>
        /// <remarks>
        /// Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <returns>DNSServer</returns>
        DNSServer CreateDNSServer(DNSServerCreate dNSServerCreate);

        /// <summary>
        /// Creates a new DNS server
        /// </summary>
        /// <remarks>
        /// Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <returns>ApiResponse of DNSServer</returns>
        ApiResponse<DNSServer> CreateDNSServerWithHttpInfo(DNSServerCreate dNSServerCreate);
        /// <summary>
        /// Lists DNS servers that belong to the user.
        /// </summary>
        /// <remarks>
        /// Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;DNSServer&gt;</returns>
        List<DNSServer> ListDNSServers();

        /// <summary>
        /// Lists DNS servers that belong to the user.
        /// </summary>
        /// <remarks>
        /// Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;DNSServer&gt;</returns>
        ApiResponse<List<DNSServer>> ListDNSServersWithHttpInfo();
        /// <summary>
        /// Updates DNS server settings
        /// </summary>
        /// <remarks>
        /// Updates the settings for a specific DNS server including user rules.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        void UpdateDNSServerSettings(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate);

        /// <summary>
        /// Updates DNS server settings
        /// </summary>
        /// <remarks>
        /// Updates the settings for a specific DNS server including user rules.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> UpdateDNSServerSettingsWithHttpInfo(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDNSServersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Creates a new DNS server
        /// </summary>
        /// <remarks>
        /// Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DNSServer</returns>
        System.Threading.Tasks.Task<DNSServer> CreateDNSServerAsync(DNSServerCreate dNSServerCreate, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Creates a new DNS server
        /// </summary>
        /// <remarks>
        /// Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DNSServer)</returns>
        System.Threading.Tasks.Task<ApiResponse<DNSServer>> CreateDNSServerWithHttpInfoAsync(DNSServerCreate dNSServerCreate, System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Lists DNS servers that belong to the user.
        /// </summary>
        /// <remarks>
        /// Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DNSServer&gt;</returns>
        System.Threading.Tasks.Task<List<DNSServer>> ListDNSServersAsync(System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Lists DNS servers that belong to the user.
        /// </summary>
        /// <remarks>
        /// Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DNSServer&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<DNSServer>>> ListDNSServersWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default);
        /// <summary>
        /// Updates DNS server settings
        /// </summary>
        /// <remarks>
        /// Updates the settings for a specific DNS server including user rules.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task UpdateDNSServerSettingsAsync(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// Updates DNS server settings
        /// </summary>
        /// <remarks>
        /// Updates the settings for a specific DNS server including user rules.
        /// </remarks>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> UpdateDNSServerSettingsWithHttpInfoAsync(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate, System.Threading.CancellationToken cancellationToken = default);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDNSServersApi : IDNSServersApiSync, IDNSServersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DNSServersApi : IDisposable, IDNSServersApi
    {
        private AdGuard.ApiClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public DNSServersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public DNSServersApi(string basePath)
        {
            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                new AdGuard.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public DNSServersApi(AdGuard.ApiClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DNSServersApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DNSServersApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                new AdGuard.ApiClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public DNSServersApi(HttpClient client, AdGuard.ApiClient.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = AdGuard.ApiClient.Client.Configuration.MergeConfigurations(
                AdGuard.ApiClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new AdGuard.ApiClient.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public DNSServersApi(AdGuard.ApiClient.Client.ISynchronousClient client, AdGuard.ApiClient.Client.IAsynchronousClient asyncClient, AdGuard.ApiClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = AdGuard.ApiClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public AdGuard.ApiClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public AdGuard.ApiClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public AdGuard.ApiClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public AdGuard.ApiClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public AdGuard.ApiClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <returns>DNSServer</returns>
        public DNSServer CreateDNSServer(DNSServerCreate dNSServerCreate)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServer> localVarResponse = CreateDNSServerWithHttpInfo(dNSServerCreate);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <returns>ApiResponse of DNSServer</returns>
        public AdGuard.ApiClient.Client.ApiResponse<DNSServer> CreateDNSServerWithHttpInfo(DNSServerCreate dNSServerCreate)
        {
            // verify the required parameter 'dNSServerCreate' is set
            if (dNSServerCreate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerCreate' when calling DNSServersApi->CreateDNSServer");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*",
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = dNSServerCreate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<DNSServer>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of DNSServer</returns>
        public async System.Threading.Tasks.Task<DNSServer> CreateDNSServerAsync(DNSServerCreate dNSServerCreate, System.Threading.CancellationToken cancellationToken = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<DNSServer> localVarResponse = await CreateDNSServerWithHttpInfoAsync(dNSServerCreate, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Creates a new DNS server Creates a new DNS server. You can attach custom settings, otherwise DNS server will be created with default settings.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dNSServerCreate"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (DNSServer)</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<DNSServer>> CreateDNSServerWithHttpInfoAsync(DNSServerCreate dNSServerCreate, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dNSServerCreate' is set
            if (dNSServerCreate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dNSServerCreate' when calling DNSServersApi->CreateDNSServer");


            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*",
                "application/json"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = dNSServerCreate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<DNSServer>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateDNSServer", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Lists DNS servers that belong to the user. Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;DNSServer&gt;</returns>
        public List<DNSServer> ListDNSServers()
        {
            AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>> localVarResponse = ListDNSServersWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Lists DNS servers that belong to the user. Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;DNSServer&gt;</returns>
        public AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>> ListDNSServersWithHttpInfo()
        {
            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<List<DNSServer>>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDNSServers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Lists DNS servers that belong to the user. Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DNSServer&gt;</returns>
        public async System.Threading.Tasks.Task<List<DNSServer>> ListDNSServersAsync(System.Threading.CancellationToken cancellationToken = default)
        {
            AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>> localVarResponse = await ListDNSServersWithHttpInfoAsync(cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Lists DNS servers that belong to the user. Lists DNS servers that belong to the user. By default there is at least one default server.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DNSServer&gt;)</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<List<DNSServer>>> ListDNSServersWithHttpInfoAsync(System.Threading.CancellationToken cancellationToken = default)
        {

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "*/*"
            };


            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);


            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<List<DNSServer>>("/oapi/v1/dns_servers", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListDNSServers", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings for a specific DNS server including user rules.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        public void UpdateDNSServerSettings(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate)
        {
            UpdateDNSServerSettingsWithHttpInfo(dnsServerId, dnsServerSettingsUpdate);
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings for a specific DNS server including user rules.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public AdGuard.ApiClient.Client.ApiResponse<Object> UpdateDNSServerSettingsWithHttpInfo(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->UpdateDNSServerSettings");

            // verify the required parameter 'dnsServerSettingsUpdate' is set
            if (dnsServerSettingsUpdate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerSettingsUpdate' when calling DNSServersApi->UpdateDNSServerSettings");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId));
            localVarRequestOptions.Data = dnsServerSettingsUpdate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/oapi/v1/dns_servers/{dns_server_id}/settings", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDNSServerSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings for a specific DNS server including user rules.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task UpdateDNSServerSettingsAsync(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate, System.Threading.CancellationToken cancellationToken = default)
        {
            await UpdateDNSServerSettingsWithHttpInfoAsync(dnsServerId, dnsServerSettingsUpdate, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Updates DNS server settings Updates the settings for a specific DNS server including user rules.
        /// </summary>
        /// <exception cref="AdGuard.ApiClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="dnsServerId">The DNS server ID.</param>
        /// <param name="dnsServerSettingsUpdate">The settings update payload.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<AdGuard.ApiClient.Client.ApiResponse<Object>> UpdateDNSServerSettingsWithHttpInfoAsync(string dnsServerId, DNSServerSettingsUpdate dnsServerSettingsUpdate, System.Threading.CancellationToken cancellationToken = default)
        {
            // verify the required parameter 'dnsServerId' is set
            if (dnsServerId == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerId' when calling DNSServersApi->UpdateDNSServerSettings");

            // verify the required parameter 'dnsServerSettingsUpdate' is set
            if (dnsServerSettingsUpdate == null)
                throw new AdGuard.ApiClient.Client.ApiException(400, "Missing required parameter 'dnsServerSettingsUpdate' when calling DNSServersApi->UpdateDNSServerSettings");

            AdGuard.ApiClient.Client.RequestOptions localVarRequestOptions = new AdGuard.ApiClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = AdGuard.ApiClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("dns_server_id", AdGuard.ApiClient.Client.ClientUtils.ParameterToString(dnsServerId));
            localVarRequestOptions.Data = dnsServerSettingsUpdate;

            // authentication (ApiKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }
            // authentication (AuthToken) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/oapi/v1/dns_servers/{dns_server_id}/settings", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateDNSServerSettings", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
