/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AdGuard.ApiClient.Model;
using AdGuard.ApiClient.Client;
using System.Reflection;
using System.Text.Json;

namespace AdGuard.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccessTokenResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessTokenResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccessTokenResponse
        //private AccessTokenResponse instance;

        public AccessTokenResponseTests()
        {
            // TODO uncomment below to create an instance of AccessTokenResponse
            //instance = new AccessTokenResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessTokenResponse
        /// </summary>
        [Fact]
        public void AccessTokenResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccessTokenResponse
            //Assert.IsType<AccessTokenResponse>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'ExpiresIn'
        /// </summary>
        [Fact]
        public void ExpiresInTest()
        {
            // TODO unit test for the property 'ExpiresIn'
        }

        /// <summary>
        /// Test the property 'RefreshToken'
        /// </summary>
        [Fact]
        public void RefreshTokenTest()
        {
            // TODO unit test for the property 'RefreshToken'
        }

        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
    }
}
