/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace AdGuard.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountLimits
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountLimitsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountLimits
        //private AccountLimits instance;

        public AccountLimitsTests()
        {
            // TODO uncomment below to create an instance of AccountLimits
            //instance = new AccountLimits();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountLimits
        /// </summary>
        [Fact]
        public void AccountLimitsInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountLimits
            //Assert.IsType<AccountLimits>(instance);
        }

        /// <summary>
        /// Test the property 'AccessRules'
        /// </summary>
        [Fact]
        public void AccessRulesTest()
        {
            // TODO unit test for the property 'AccessRules'
        }

        /// <summary>
        /// Test the property 'DedicatedIpv4'
        /// </summary>
        [Fact]
        public void DedicatedIpv4Test()
        {
            // TODO unit test for the property 'DedicatedIpv4'
        }

        /// <summary>
        /// Test the property 'Devices'
        /// </summary>
        [Fact]
        public void DevicesTest()
        {
            // TODO unit test for the property 'Devices'
        }

        /// <summary>
        /// Test the property 'DnsServers'
        /// </summary>
        [Fact]
        public void DnsServersTest()
        {
            // TODO unit test for the property 'DnsServers'
        }

        /// <summary>
        /// Test the property 'Requests'
        /// </summary>
        [Fact]
        public void RequestsTest()
        {
            // TODO unit test for the property 'Requests'
        }

        /// <summary>
        /// Test the property 'UserRules'
        /// </summary>
        [Fact]
        public void UserRulesTest()
        {
            // TODO unit test for the property 'UserRules'
        }
    }
}
