/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AdGuard.ApiClient.Model;
using AdGuard.ApiClient.Client;
using System.Reflection;
using System.Text.Json;

namespace AdGuard.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceUpdate
        //private DeviceUpdate instance;

        public DeviceUpdateTests()
        {
            // TODO uncomment below to create an instance of DeviceUpdate
            //instance = new DeviceUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceUpdate
        /// </summary>
        [Fact]
        public void DeviceUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceUpdate
            //Assert.IsType<DeviceUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Fact]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }

        /// <summary>
        /// Test the property 'DnsServerId'
        /// </summary>
        [Fact]
        public void DnsServerIdTest()
        {
            // TODO unit test for the property 'DnsServerId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
