#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'BlockingModeSettingsUpdate' {
    Context 'BlockingModeSettingsUpdate' {
        It 'Initialize-BlockingModeSettingsUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-BlockingModeSettingsUpdate -BlockingMode "TEST_VALUE" -Ipv4BlockingAddress "TEST_VALUE" -Ipv6BlockingAddress "TEST_VALUE"
            #$NewObject | Should -BeOfType BlockingModeSettingsUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
