#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'CompanyQueriesStats' {
    Context 'CompanyQueriesStats' {
        It 'Initialize-CompanyQueriesStats' {
            # a simple test to create an object
            #$NewObject = Initialize-CompanyQueriesStats -CompanyName "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType CompanyQueriesStats
            #$NewObject.property | Should -Be 0
        }
    }
}
