#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'CompanyQueriesStatsList' {
    Context 'CompanyQueriesStatsList' {
        It 'Initialize-CompanyQueriesStatsList' {
            # a simple test to create an object
            #$NewObject = Initialize-CompanyQueriesStatsList -Stats "TEST_VALUE"
            #$NewObject | Should -BeOfType CompanyQueriesStatsList
            #$NewObject.property | Should -Be 0
        }
    }
}
