#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'CountryQueriesStatsList' {
    Context 'CountryQueriesStatsList' {
        It 'Initialize-CountryQueriesStatsList' {
            # a simple test to create an object
            #$NewObject = Initialize-CountryQueriesStatsList -Stats "TEST_VALUE"
            #$NewObject | Should -BeOfType CountryQueriesStatsList
            #$NewObject.property | Should -Be 0
        }
    }
}
