#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DedicatedIps' {
    Context 'DedicatedIps' {
        It 'Initialize-DedicatedIps' {
            # a simple test to create an object
            #$NewObject = Initialize-DedicatedIps -Ipv4 "TEST_VALUE" -Ipv4Limit "TEST_VALUE" -Ipv6 "TEST_VALUE"
            #$NewObject | Should -BeOfType DedicatedIps
            #$NewObject.property | Should -Be 0
        }
    }
}
