#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DedicatedIPv4Address' {
    Context 'DedicatedIPv4Address' {
        It 'Initialize-DedicatedIPv4Address' {
            # a simple test to create an object
            #$NewObject = Initialize-DedicatedIPv4Address -DeviceId "TEST_VALUE" -Ip "TEST_VALUE"
            #$NewObject | Should -BeOfType DedicatedIPv4Address
            #$NewObject.property | Should -Be 0
        }
    }
}
