#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DeviceSettingsUpdate' {
    Context 'DeviceSettingsUpdate' {
        It 'Initialize-DeviceSettingsUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-DeviceSettingsUpdate -DetectDohAuthOnly "TEST_VALUE" -ProtectionEnabled "TEST_VALUE"
            #$NewObject | Should -BeOfType DeviceSettingsUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
