#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DeviceUpdate' {
    Context 'DeviceUpdate' {
        It 'Initialize-DeviceUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-DeviceUpdate -DeviceType "TEST_VALUE" -DnsServerId "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType DeviceUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
