#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'Device' {
    Context 'Device' {
        It 'Initialize-Device' {
            # a simple test to create an object
            #$NewObject = Initialize-Device -DeviceType "TEST_VALUE" -DnsAddresses "TEST_VALUE" -DnsServerId "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Settings "TEST_VALUE"
            #$NewObject | Should -BeOfType Device
            #$NewObject.property | Should -Be 0
        }
    }
}
