#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DeviceQueriesStats' {
    Context 'DeviceQueriesStats' {
        It 'Initialize-DeviceQueriesStats' {
            # a simple test to create an object
            #$NewObject = Initialize-DeviceQueriesStats -DeviceId "TEST_VALUE" -LastActivityTimeMillis "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType DeviceQueriesStats
            #$NewObject.property | Should -Be 0
        }
    }
}
