#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DNSServerSettingsUpdate' {
    Context 'DNSServerSettingsUpdate' {
        It 'Initialize-DNSServerSettingsUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-DNSServerSettingsUpdate -AccessSettings "TEST_VALUE" -AutoConnectDevicesEnabled "TEST_VALUE" -BlockChromePrefetch "TEST_VALUE" -BlockFirefoxCanary "TEST_VALUE" -BlockPrivateRelay "TEST_VALUE" -BlockTtlSeconds "TEST_VALUE" -BlockingModeSettings "TEST_VALUE" -FilterListsSettings "TEST_VALUE" -IpLogEnabled "TEST_VALUE" -ParentalControlSettings "TEST_VALUE" -ProtectionEnabled "TEST_VALUE" -SafebrowsingSettings "TEST_VALUE" -UserRulesSettings "TEST_VALUE"
            #$NewObject | Should -BeOfType DNSServerSettingsUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
