#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'DNSServer' {
    Context 'DNSServer' {
        It 'Initialize-DNSServer' {
            # a simple test to create an object
            #$NewObject = Initialize-DNSServer -Default "TEST_VALUE" -DeviceIds "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE" -Settings "TEST_VALUE"
            #$NewObject | Should -BeOfType DNSServer
            #$NewObject.property | Should -Be 0
        }
    }
}
