#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FieldError' {
    Context 'FieldError' {
        It 'Initialize-FieldError' {
            # a simple test to create an object
            #$NewObject = Initialize-FieldError -ErrorCode "TEST_VALUE" -Field "TEST_VALUE" -Message "TEST_VALUE"
            #$NewObject | Should -BeOfType FieldError
            #$NewObject.property | Should -Be 0
        }
    }
}
