#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FilterListCategory' {
    Context 'FilterListCategory' {
        It 'Initialize-FilterListCategory' {
            # a simple test to create an object
            #$NewObject = Initialize-FilterListCategory -Category "TEST_VALUE" -Description "TEST_VALUE" -Value "TEST_VALUE"
            #$NewObject | Should -BeOfType FilterListCategory
            #$NewObject.property | Should -Be 0
        }
    }
}
