#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FilteringActionSource' {
    Context 'FilteringActionSource' {
        It 'Initialize-FilteringActionSource' {
            # a simple test to create an object
            #$NewObject = Initialize-FilteringActionSource
            #$NewObject | Should -BeOfType FilteringActionSource
            #$NewObject.property | Should -Be 0
        }
    }
}
