#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FilterListsSettingsUpdate' {
    Context 'FilterListsSettingsUpdate' {
        It 'Initialize-FilterListsSettingsUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-FilterListsSettingsUpdate -Enabled "TEST_VALUE" -FilterList "TEST_VALUE"
            #$NewObject | Should -BeOfType FilterListsSettingsUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
