#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FilterListItem' {
    Context 'FilterListItem' {
        It 'Initialize-FilterListItem' {
            # a simple test to create an object
            #$NewObject = Initialize-FilterListItem -Enabled "TEST_VALUE" -FilterId "TEST_VALUE"
            #$NewObject | Should -BeOfType FilterListItem
            #$NewObject.property | Should -Be 0
        }
    }
}
