#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FilterListItemUpdate' {
    Context 'FilterListItemUpdate' {
        It 'Initialize-FilterListItemUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-FilterListItemUpdate -Enabled "TEST_VALUE" -FilterId "TEST_VALUE"
            #$NewObject | Should -BeOfType FilterListItemUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
