#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FilterListCategoryType' {
    Context 'FilterListCategoryType' {
        It 'Initialize-FilterListCategoryType' {
            # a simple test to create an object
            #$NewObject = Initialize-FilterListCategoryType
            #$NewObject | Should -BeOfType FilterListCategoryType
            #$NewObject.property | Should -Be 0
        }
    }
}
