#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'FilteringInfo' {
    Context 'FilteringInfo' {
        It 'Initialize-FilteringInfo' {
            # a simple test to create an object
            #$NewObject = Initialize-FilteringInfo -BlockedServiceId "TEST_VALUE" -FilterId "TEST_VALUE" -FilterRule "TEST_VALUE" -FilteringStatus "TEST_VALUE" -FilteringType "TEST_VALUE"
            #$NewObject | Should -BeOfType FilteringInfo
            #$NewObject.property | Should -Be 0
        }
    }
}
