#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'IpType' {
    Context 'IpType' {
        It 'Initialize-IpType' {
            # a simple test to create an object
            #$NewObject = Initialize-IpType
            #$NewObject | Should -BeOfType IpType
            #$NewObject.property | Should -Be 0
        }
    }
}
