#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'Page' {
    Context 'Page' {
        It 'Initialize-Page' {
            # a simple test to create an object
            #$NewObject = Initialize-Page -Current "TEST_VALUE" -PageCursor "TEST_VALUE" -PageNumber "TEST_VALUE"
            #$NewObject | Should -BeOfType Page
            #$NewObject.property | Should -Be 0
        }
    }
}
