#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'ParentalControlSettingsUpdate' {
    Context 'ParentalControlSettingsUpdate' {
        It 'Initialize-ParentalControlSettingsUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-ParentalControlSettingsUpdate -BlockAdultWebsitesEnabled "TEST_VALUE" -BlockedServices "TEST_VALUE" -Enabled "TEST_VALUE" -EnginesSafeSearchEnabled "TEST_VALUE" -ScreenTimeSchedule "TEST_VALUE" -YoutubeSafeSearchEnabled "TEST_VALUE"
            #$NewObject | Should -BeOfType ParentalControlSettingsUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
