#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'QueryLogItem' {
    Context 'QueryLogItem' {
        It 'Initialize-QueryLogItem' {
            # a simple test to create an object
            #$NewObject = Initialize-QueryLogItem -Asn "TEST_VALUE" -CategoryType "TEST_VALUE" -ClientCountry "TEST_VALUE" -CompanyId "TEST_VALUE" -DeviceId "TEST_VALUE" -DnsProtoType "TEST_VALUE" -DnsRequestType "TEST_VALUE" -DnsResponseType "TEST_VALUE" -Dnssec "TEST_VALUE" -Domain "TEST_VALUE" -FilteringInfo "TEST_VALUE" -Network "TEST_VALUE" -ResponseCountry "TEST_VALUE" -TimeIso "TEST_VALUE" -TimeMillis "TEST_VALUE"
            #$NewObject | Should -BeOfType QueryLogItem
            #$NewObject.property | Should -Be 0
        }
    }
}
