#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'ScheduleDay' {
    Context 'ScheduleDay' {
        It 'Initialize-ScheduleDay' {
            # a simple test to create an object
            #$NewObject = Initialize-ScheduleDay -DayOfWeek "TEST_VALUE" -Enabled "TEST_VALUE" -FromTime "TEST_VALUE" -ToTime "TEST_VALUE"
            #$NewObject | Should -BeOfType ScheduleDay
            #$NewObject.property | Should -Be 0
        }
    }
}
