#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'SecureDnsProtoType' {
    Context 'SecureDnsProtoType' {
        It 'Initialize-SecureDnsProtoType' {
            # a simple test to create an object
            #$NewObject = Initialize-SecureDnsProtoType
            #$NewObject | Should -BeOfType SecureDnsProtoType
            #$NewObject.property | Should -Be 0
        }
    }
}
