#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'UserRulesSettingsUpdate' {
    Context 'UserRulesSettingsUpdate' {
        It 'Initialize-UserRulesSettingsUpdate' {
            # a simple test to create an object
            #$NewObject = Initialize-UserRulesSettingsUpdate -Enabled "TEST_VALUE" -Rules "TEST_VALUE"
            #$NewObject | Should -BeOfType UserRulesSettingsUpdate
            #$NewObject.property | Should -Be 0
        }
    }
}
