#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

Describe -tag 'PSAdGuardDNS' -name 'WebService' {
    Context 'WebService' {
        It 'Initialize-WebService' {
            # a simple test to create an object
            #$NewObject = Initialize-WebService -IconSvg "TEST_VALUE" -Id "TEST_VALUE" -Name "TEST_VALUE"
            #$NewObject | Should -BeOfType WebService
            #$NewObject.property | Should -Be 0
        }
    }
}
