#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Access token success response

.PARAMETER AccessToken
Access token
.PARAMETER ExpiresIn
The lifetime in seconds of the access token
.PARAMETER RefreshToken
Refresh token
.PARAMETER TokenType
The type of the token issued
.OUTPUTS

AccessTokenResponse<PSCustomObject>
#>

function Initialize-AccessTokenResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${AccessToken},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${ExpiresIn},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${RefreshToken},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${TokenType}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => AccessTokenResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ExpiresIn) {
            throw "invalid value for 'ExpiresIn', 'ExpiresIn' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "access_token" = ${AccessToken}
            "expires_in" = ${ExpiresIn}
            "refresh_token" = ${RefreshToken}
            "token_type" = ${TokenType}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AccessTokenResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to AccessTokenResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AccessTokenResponse<PSCustomObject>
#>
function ConvertFrom-JsonToAccessTokenResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => AccessTokenResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AccessTokenResponse
        $AllProperties = ("access_token", "expires_in", "refresh_token", "token_type")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'expires_in' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "expires_in"))) {
            throw "Error! JSON cannot be serialized due to the required property 'expires_in' missing."
        } else {
            $ExpiresIn = $JsonParameters.PSobject.Properties["expires_in"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "access_token"))) { #optional property not found
            $AccessToken = $null
        } else {
            $AccessToken = $JsonParameters.PSobject.Properties["access_token"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "refresh_token"))) { #optional property not found
            $RefreshToken = $null
        } else {
            $RefreshToken = $JsonParameters.PSobject.Properties["refresh_token"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "token_type"))) { #optional property not found
            $TokenType = $null
        } else {
            $TokenType = $JsonParameters.PSobject.Properties["token_type"].value
        }

        $PSO = [PSCustomObject]@{
            "access_token" = ${AccessToken}
            "expires_in" = ${ExpiresIn}
            "refresh_token" = ${RefreshToken}
            "token_type" = ${TokenType}
        }

        return $PSO
    }

}

