#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Access token error response

.PARAMETER VarError
Error type
.PARAMETER ErrorCode
Error code
.PARAMETER ErrorDescription
Error description
.OUTPUTS

AccessTokenErrorResponse<PSCustomObject>
#>

function Initialize-AccessTokenErrorResponse {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${VarError},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ErrorCode},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ErrorDescription}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => AccessTokenErrorResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "error" = ${VarError}
            "error_code" = ${ErrorCode}
            "error_description" = ${ErrorDescription}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AccessTokenErrorResponse<PSCustomObject>

.DESCRIPTION

Convert from JSON to AccessTokenErrorResponse<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AccessTokenErrorResponse<PSCustomObject>
#>
function ConvertFrom-JsonToAccessTokenErrorResponse {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => AccessTokenErrorResponse' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AccessTokenErrorResponse
        $AllProperties = ("error", "error_code", "error_description")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "error"))) { #optional property not found
            $VarError = $null
        } else {
            $VarError = $JsonParameters.PSobject.Properties["error"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "error_code"))) { #optional property not found
            $ErrorCode = $null
        } else {
            $ErrorCode = $JsonParameters.PSobject.Properties["error_code"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "error_description"))) { #optional property not found
            $ErrorDescription = $null
        } else {
            $ErrorDescription = $JsonParameters.PSobject.Properties["error_description"].value
        }

        $PSO = [PSCustomObject]@{
            "error" = ${VarError}
            "error_code" = ${ErrorCode}
            "error_description" = ${ErrorDescription}
        }

        return $PSO
    }

}

