#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Account limits

.PARAMETER AccessRules
No description available.
.PARAMETER DedicatedIpv4
No description available.
.PARAMETER Devices
No description available.
.PARAMETER DnsServers
No description available.
.PARAMETER Requests
No description available.
.PARAMETER UserRules
No description available.
.OUTPUTS

AccountLimits<PSCustomObject>
#>

function Initialize-AccountLimits {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AccessRules},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DedicatedIpv4},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Devices},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DnsServers},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Requests},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${UserRules}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => AccountLimits' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $AccessRules) {
            throw "invalid value for 'AccessRules', 'AccessRules' cannot be null."
        }

        if ($null -eq $DedicatedIpv4) {
            throw "invalid value for 'DedicatedIpv4', 'DedicatedIpv4' cannot be null."
        }

        if ($null -eq $Devices) {
            throw "invalid value for 'Devices', 'Devices' cannot be null."
        }

        if ($null -eq $DnsServers) {
            throw "invalid value for 'DnsServers', 'DnsServers' cannot be null."
        }

        if ($null -eq $Requests) {
            throw "invalid value for 'Requests', 'Requests' cannot be null."
        }

        if ($null -eq $UserRules) {
            throw "invalid value for 'UserRules', 'UserRules' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "access_rules" = ${AccessRules}
            "dedicated_ipv4" = ${DedicatedIpv4}
            "devices" = ${Devices}
            "dns_servers" = ${DnsServers}
            "requests" = ${Requests}
            "user_rules" = ${UserRules}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to AccountLimits<PSCustomObject>

.DESCRIPTION

Convert from JSON to AccountLimits<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

AccountLimits<PSCustomObject>
#>
function ConvertFrom-JsonToAccountLimits {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => AccountLimits' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in AccountLimits
        $AllProperties = ("access_rules", "dedicated_ipv4", "devices", "dns_servers", "requests", "user_rules")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'access_rules' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "access_rules"))) {
            throw "Error! JSON cannot be serialized due to the required property 'access_rules' missing."
        } else {
            $AccessRules = $JsonParameters.PSobject.Properties["access_rules"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dedicated_ipv4"))) {
            throw "Error! JSON cannot be serialized due to the required property 'dedicated_ipv4' missing."
        } else {
            $DedicatedIpv4 = $JsonParameters.PSobject.Properties["dedicated_ipv4"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "devices"))) {
            throw "Error! JSON cannot be serialized due to the required property 'devices' missing."
        } else {
            $Devices = $JsonParameters.PSobject.Properties["devices"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dns_servers"))) {
            throw "Error! JSON cannot be serialized due to the required property 'dns_servers' missing."
        } else {
            $DnsServers = $JsonParameters.PSobject.Properties["dns_servers"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "requests"))) {
            throw "Error! JSON cannot be serialized due to the required property 'requests' missing."
        } else {
            $Requests = $JsonParameters.PSobject.Properties["requests"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "user_rules"))) {
            throw "Error! JSON cannot be serialized due to the required property 'user_rules' missing."
        } else {
            $UserRules = $JsonParameters.PSobject.Properties["user_rules"].value
        }

        $PSO = [PSCustomObject]@{
            "access_rules" = ${AccessRules}
            "dedicated_ipv4" = ${DedicatedIpv4}
            "devices" = ${Devices}
            "dns_servers" = ${DnsServers}
            "requests" = ${Requests}
            "user_rules" = ${UserRules}
        }

        return $PSO
    }

}

