#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Countries queries statistics

.PARAMETER Stats
List of queries stats
.OUTPUTS

CountryQueriesStatsList<PSCustomObject>
#>

function Initialize-CountryQueriesStatsList {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Stats}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => CountryQueriesStatsList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Stats) {
            throw "invalid value for 'Stats', 'Stats' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "stats" = ${Stats}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to CountryQueriesStatsList<PSCustomObject>

.DESCRIPTION

Convert from JSON to CountryQueriesStatsList<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

CountryQueriesStatsList<PSCustomObject>
#>
function ConvertFrom-JsonToCountryQueriesStatsList {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => CountryQueriesStatsList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in CountryQueriesStatsList
        $AllProperties = ("stats")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'stats' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "stats"))) {
            throw "Error! JSON cannot be serialized due to the required property 'stats' missing."
        } else {
            $Stats = $JsonParameters.PSobject.Properties["stats"].value
        }

        $PSO = [PSCustomObject]@{
            "stats" = ${Stats}
        }

        return $PSO
    }

}

