#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum DayOfWeek.

.DESCRIPTION

Day of week
#>

enum DayOfWeek {
    # enum value: "MONDAY"
    MONDAY
    # enum value: "TUESDAY"
    TUESDAY
    # enum value: "WEDNESDAY"
    WEDNESDAY
    # enum value: "THURSDAY"
    THURSDAY
    # enum value: "FRIDAY"
    FRIDAY
    # enum value: "SATURDAY"
    SATURDAY
    # enum value: "SUNDAY"
    SUNDAY
}

