#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Dedicated IPs

.PARAMETER Ipv4
Dedicated IPv4 address
.PARAMETER Ipv4Limit
No description available.
.PARAMETER Ipv6
Dedicated IPv6 address
.OUTPUTS

DedicatedIps<PSCustomObject>
#>

function Initialize-DedicatedIps {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Ipv4},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Ipv4Limit},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Ipv6}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DedicatedIps' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Ipv4) {
            throw "invalid value for 'Ipv4', 'Ipv4' cannot be null."
        }

        if ($null -eq $Ipv4Limit) {
            throw "invalid value for 'Ipv4Limit', 'Ipv4Limit' cannot be null."
        }

        if ($null -eq $Ipv6) {
            throw "invalid value for 'Ipv6', 'Ipv6' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "ipv4" = ${Ipv4}
            "ipv4_limit" = ${Ipv4Limit}
            "ipv6" = ${Ipv6}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DedicatedIps<PSCustomObject>

.DESCRIPTION

Convert from JSON to DedicatedIps<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DedicatedIps<PSCustomObject>
#>
function ConvertFrom-JsonToDedicatedIps {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DedicatedIps' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DedicatedIps
        $AllProperties = ("ipv4", "ipv4_limit", "ipv6")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'ipv4' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ipv4"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ipv4' missing."
        } else {
            $Ipv4 = $JsonParameters.PSobject.Properties["ipv4"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ipv4_limit"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ipv4_limit' missing."
        } else {
            $Ipv4Limit = $JsonParameters.PSobject.Properties["ipv4_limit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ipv6"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ipv6' missing."
        } else {
            $Ipv6 = $JsonParameters.PSobject.Properties["ipv6"].value
        }

        $PSO = [PSCustomObject]@{
            "ipv4" = ${Ipv4}
            "ipv4_limit" = ${Ipv4Limit}
            "ipv6" = ${Ipv6}
        }

        return $PSO
    }

}

