#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Device

.PARAMETER DeviceType
No description available.
.PARAMETER DnsAddresses
No description available.
.PARAMETER DnsServerId
DNS server ID
.PARAMETER Id
Device ID
.PARAMETER Name
Device name
.PARAMETER Settings
No description available.
.OUTPUTS

Device<PSCustomObject>
#>

function Initialize-Device {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("WINDOWS", "ANDROID", "MAC", "IOS", "LINUX", "ROUTER", "SMART_TV", "GAME_CONSOLE", "UNKNOWN")]
        [PSCustomObject]
        ${DeviceType},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DnsAddresses},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DnsServerId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${Settings}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => Device' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $DeviceType) {
            throw "invalid value for 'DeviceType', 'DeviceType' cannot be null."
        }

        if ($null -eq $DnsAddresses) {
            throw "invalid value for 'DnsAddresses', 'DnsAddresses' cannot be null."
        }

        if ($null -eq $DnsServerId) {
            throw "invalid value for 'DnsServerId', 'DnsServerId' cannot be null."
        }

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $Settings) {
            throw "invalid value for 'Settings', 'Settings' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "device_type" = ${DeviceType}
            "dns_addresses" = ${DnsAddresses}
            "dns_server_id" = ${DnsServerId}
            "id" = ${Id}
            "name" = ${Name}
            "settings" = ${Settings}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Device<PSCustomObject>

.DESCRIPTION

Convert from JSON to Device<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Device<PSCustomObject>
#>
function ConvertFrom-JsonToDevice {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => Device' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Device
        $AllProperties = ("device_type", "dns_addresses", "dns_server_id", "id", "name", "settings")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'device_type' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "device_type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'device_type' missing."
        } else {
            $DeviceType = $JsonParameters.PSobject.Properties["device_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dns_addresses"))) {
            throw "Error! JSON cannot be serialized due to the required property 'dns_addresses' missing."
        } else {
            $DnsAddresses = $JsonParameters.PSobject.Properties["dns_addresses"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dns_server_id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'dns_server_id' missing."
        } else {
            $DnsServerId = $JsonParameters.PSobject.Properties["dns_server_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "settings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'settings' missing."
        } else {
            $Settings = $JsonParameters.PSobject.Properties["settings"].value
        }

        $PSO = [PSCustomObject]@{
            "device_type" = ${DeviceType}
            "dns_addresses" = ${DnsAddresses}
            "dns_server_id" = ${DnsServerId}
            "id" = ${Id}
            "name" = ${Name}
            "settings" = ${Settings}
        }

        return $PSO
    }

}

