#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Device settings update

.PARAMETER DetectDohAuthOnly
Use only DNS-over-HTTPS with authentication
.PARAMETER ProtectionEnabled
Enable protection
.OUTPUTS

DeviceSettingsUpdate<PSCustomObject>
#>

function Initialize-DeviceSettingsUpdate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${DetectDohAuthOnly},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${ProtectionEnabled}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DeviceSettingsUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "detect_doh_auth_only" = ${DetectDohAuthOnly}
            "protection_enabled" = ${ProtectionEnabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DeviceSettingsUpdate<PSCustomObject>

.DESCRIPTION

Convert from JSON to DeviceSettingsUpdate<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DeviceSettingsUpdate<PSCustomObject>
#>
function ConvertFrom-JsonToDeviceSettingsUpdate {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DeviceSettingsUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DeviceSettingsUpdate
        $AllProperties = ("detect_doh_auth_only", "protection_enabled")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "detect_doh_auth_only"))) { #optional property not found
            $DetectDohAuthOnly = $null
        } else {
            $DetectDohAuthOnly = $JsonParameters.PSobject.Properties["detect_doh_auth_only"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "protection_enabled"))) { #optional property not found
            $ProtectionEnabled = $null
        } else {
            $ProtectionEnabled = $JsonParameters.PSobject.Properties["protection_enabled"].value
        }

        $PSO = [PSCustomObject]@{
            "detect_doh_auth_only" = ${DetectDohAuthOnly}
            "protection_enabled" = ${ProtectionEnabled}
        }

        return $PSO
    }

}

