#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

DNS server settings

.PARAMETER AccessSettings
No description available.
.PARAMETER AutoConnectDevicesEnabled
Approval for auto-connecting devices through a specific link type
.PARAMETER BlockChromePrefetch
Block prefetch proxy in Google chrome
.PARAMETER BlockFirefoxCanary
If Firefox Canary should be blocked
.PARAMETER BlockPrivateRelay
Is private relay should be blocked
.PARAMETER BlockTtlSeconds
TTL for blocked request
.PARAMETER BlockingModeSettings
No description available.
.PARAMETER FilterListsSettings
No description available.
.PARAMETER IpLogEnabled
Consent to log IP addresses of requests
.PARAMETER ParentalControlSettings
No description available.
.PARAMETER ProtectionEnabled
Is protection enabled
.PARAMETER SafebrowsingSettings
No description available.
.PARAMETER UserRulesSettings
No description available.
.OUTPUTS

DNSServerSettings<PSCustomObject>
#>

function Initialize-DNSServerSettings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${AccessSettings},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${AutoConnectDevicesEnabled},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${BlockChromePrefetch},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${BlockFirefoxCanary},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${BlockPrivateRelay},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${BlockTtlSeconds},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${BlockingModeSettings},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${FilterListsSettings},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${IpLogEnabled},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ParentalControlSettings},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${ProtectionEnabled},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${SafebrowsingSettings},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${UserRulesSettings}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DNSServerSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $AccessSettings) {
            throw "invalid value for 'AccessSettings', 'AccessSettings' cannot be null."
        }

        if ($null -eq $AutoConnectDevicesEnabled) {
            throw "invalid value for 'AutoConnectDevicesEnabled', 'AutoConnectDevicesEnabled' cannot be null."
        }

        if ($null -eq $BlockChromePrefetch) {
            throw "invalid value for 'BlockChromePrefetch', 'BlockChromePrefetch' cannot be null."
        }

        if ($null -eq $BlockFirefoxCanary) {
            throw "invalid value for 'BlockFirefoxCanary', 'BlockFirefoxCanary' cannot be null."
        }

        if ($null -eq $BlockPrivateRelay) {
            throw "invalid value for 'BlockPrivateRelay', 'BlockPrivateRelay' cannot be null."
        }

        if ($null -eq $BlockTtlSeconds) {
            throw "invalid value for 'BlockTtlSeconds', 'BlockTtlSeconds' cannot be null."
        }

        if ($null -eq $BlockingModeSettings) {
            throw "invalid value for 'BlockingModeSettings', 'BlockingModeSettings' cannot be null."
        }

        if ($null -eq $FilterListsSettings) {
            throw "invalid value for 'FilterListsSettings', 'FilterListsSettings' cannot be null."
        }

        if ($null -eq $IpLogEnabled) {
            throw "invalid value for 'IpLogEnabled', 'IpLogEnabled' cannot be null."
        }

        if ($null -eq $ParentalControlSettings) {
            throw "invalid value for 'ParentalControlSettings', 'ParentalControlSettings' cannot be null."
        }

        if ($null -eq $ProtectionEnabled) {
            throw "invalid value for 'ProtectionEnabled', 'ProtectionEnabled' cannot be null."
        }

        if ($null -eq $SafebrowsingSettings) {
            throw "invalid value for 'SafebrowsingSettings', 'SafebrowsingSettings' cannot be null."
        }

        if ($null -eq $UserRulesSettings) {
            throw "invalid value for 'UserRulesSettings', 'UserRulesSettings' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "access_settings" = ${AccessSettings}
            "auto_connect_devices_enabled" = ${AutoConnectDevicesEnabled}
            "block_chrome_prefetch" = ${BlockChromePrefetch}
            "block_firefox_canary" = ${BlockFirefoxCanary}
            "block_private_relay" = ${BlockPrivateRelay}
            "block_ttl_seconds" = ${BlockTtlSeconds}
            "blocking_mode_settings" = ${BlockingModeSettings}
            "filter_lists_settings" = ${FilterListsSettings}
            "ip_log_enabled" = ${IpLogEnabled}
            "parental_control_settings" = ${ParentalControlSettings}
            "protection_enabled" = ${ProtectionEnabled}
            "safebrowsing_settings" = ${SafebrowsingSettings}
            "user_rules_settings" = ${UserRulesSettings}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DNSServerSettings<PSCustomObject>

.DESCRIPTION

Convert from JSON to DNSServerSettings<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DNSServerSettings<PSCustomObject>
#>
function ConvertFrom-JsonToDNSServerSettings {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DNSServerSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DNSServerSettings
        $AllProperties = ("access_settings", "auto_connect_devices_enabled", "block_chrome_prefetch", "block_firefox_canary", "block_private_relay", "block_ttl_seconds", "blocking_mode_settings", "filter_lists_settings", "ip_log_enabled", "parental_control_settings", "protection_enabled", "safebrowsing_settings", "user_rules_settings")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'access_settings' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "access_settings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'access_settings' missing."
        } else {
            $AccessSettings = $JsonParameters.PSobject.Properties["access_settings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "auto_connect_devices_enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'auto_connect_devices_enabled' missing."
        } else {
            $AutoConnectDevicesEnabled = $JsonParameters.PSobject.Properties["auto_connect_devices_enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "block_chrome_prefetch"))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_chrome_prefetch' missing."
        } else {
            $BlockChromePrefetch = $JsonParameters.PSobject.Properties["block_chrome_prefetch"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "block_firefox_canary"))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_firefox_canary' missing."
        } else {
            $BlockFirefoxCanary = $JsonParameters.PSobject.Properties["block_firefox_canary"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "block_private_relay"))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_private_relay' missing."
        } else {
            $BlockPrivateRelay = $JsonParameters.PSobject.Properties["block_private_relay"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "block_ttl_seconds"))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_ttl_seconds' missing."
        } else {
            $BlockTtlSeconds = $JsonParameters.PSobject.Properties["block_ttl_seconds"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blocking_mode_settings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'blocking_mode_settings' missing."
        } else {
            $BlockingModeSettings = $JsonParameters.PSobject.Properties["blocking_mode_settings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "filter_lists_settings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'filter_lists_settings' missing."
        } else {
            $FilterListsSettings = $JsonParameters.PSobject.Properties["filter_lists_settings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ip_log_enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ip_log_enabled' missing."
        } else {
            $IpLogEnabled = $JsonParameters.PSobject.Properties["ip_log_enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "parental_control_settings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'parental_control_settings' missing."
        } else {
            $ParentalControlSettings = $JsonParameters.PSobject.Properties["parental_control_settings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "protection_enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'protection_enabled' missing."
        } else {
            $ProtectionEnabled = $JsonParameters.PSobject.Properties["protection_enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "safebrowsing_settings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'safebrowsing_settings' missing."
        } else {
            $SafebrowsingSettings = $JsonParameters.PSobject.Properties["safebrowsing_settings"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "user_rules_settings"))) {
            throw "Error! JSON cannot be serialized due to the required property 'user_rules_settings' missing."
        } else {
            $UserRulesSettings = $JsonParameters.PSobject.Properties["user_rules_settings"].value
        }

        $PSO = [PSCustomObject]@{
            "access_settings" = ${AccessSettings}
            "auto_connect_devices_enabled" = ${AutoConnectDevicesEnabled}
            "block_chrome_prefetch" = ${BlockChromePrefetch}
            "block_firefox_canary" = ${BlockFirefoxCanary}
            "block_private_relay" = ${BlockPrivateRelay}
            "block_ttl_seconds" = ${BlockTtlSeconds}
            "blocking_mode_settings" = ${BlockingModeSettings}
            "filter_lists_settings" = ${FilterListsSettings}
            "ip_log_enabled" = ${IpLogEnabled}
            "parental_control_settings" = ${ParentalControlSettings}
            "protection_enabled" = ${ProtectionEnabled}
            "safebrowsing_settings" = ${SafebrowsingSettings}
            "user_rules_settings" = ${UserRulesSettings}
        }

        return $PSO
    }

}

