#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

DNS server access settings update

.PARAMETER AllowedClients
Allowed IP's, CIDR's or ASN's
.PARAMETER BlockKnownScanners
If known scanners should be blocked
.PARAMETER BlockedClients
Blocked IP's, CIDR's or ASN's
.PARAMETER BlockedDomainRules
Blocked domain rules
.PARAMETER Enabled
Flag that access settings are enabled
.OUTPUTS

DNSServerAccessSettingsUpdate<PSCustomObject>
#>

function Initialize-DNSServerAccessSettingsUpdate {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${AllowedClients},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${BlockKnownScanners},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${BlockedClients},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${BlockedDomainRules},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Boolean]]
        ${Enabled}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DNSServerAccessSettingsUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "allowed_clients" = ${AllowedClients}
            "block_known_scanners" = ${BlockKnownScanners}
            "blocked_clients" = ${BlockedClients}
            "blocked_domain_rules" = ${BlockedDomainRules}
            "enabled" = ${Enabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DNSServerAccessSettingsUpdate<PSCustomObject>

.DESCRIPTION

Convert from JSON to DNSServerAccessSettingsUpdate<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DNSServerAccessSettingsUpdate<PSCustomObject>
#>
function ConvertFrom-JsonToDNSServerAccessSettingsUpdate {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DNSServerAccessSettingsUpdate' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DNSServerAccessSettingsUpdate
        $AllProperties = ("allowed_clients", "block_known_scanners", "blocked_clients", "blocked_domain_rules", "enabled")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "allowed_clients"))) { #optional property not found
            $AllowedClients = $null
        } else {
            $AllowedClients = $JsonParameters.PSobject.Properties["allowed_clients"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "block_known_scanners"))) { #optional property not found
            $BlockKnownScanners = $null
        } else {
            $BlockKnownScanners = $JsonParameters.PSobject.Properties["block_known_scanners"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blocked_clients"))) { #optional property not found
            $BlockedClients = $null
        } else {
            $BlockedClients = $JsonParameters.PSobject.Properties["blocked_clients"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blocked_domain_rules"))) { #optional property not found
            $BlockedDomainRules = $null
        } else {
            $BlockedDomainRules = $JsonParameters.PSobject.Properties["blocked_domain_rules"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) { #optional property not found
            $Enabled = $null
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        $PSO = [PSCustomObject]@{
            "allowed_clients" = ${AllowedClients}
            "block_known_scanners" = ${BlockKnownScanners}
            "blocked_clients" = ${BlockedClients}
            "blocked_domain_rules" = ${BlockedDomainRules}
            "enabled" = ${Enabled}
        }

        return $PSO
    }

}

