#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

DNS server access settings

.PARAMETER AllowedClients
Allowed IP's, CIDR's or ASN's
.PARAMETER BlockKnownScanners
If known scanners should be blocked
.PARAMETER BlockedClients
Blocked IP's, CIDR's or ASN's
.PARAMETER BlockedDomainRules
Blocked domain rules
.PARAMETER Enabled
Flag that access settings are enabled
.OUTPUTS

DNSServerAccessSettings<PSCustomObject>
#>

function Initialize-DNSServerAccessSettings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${AllowedClients},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${BlockKnownScanners},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${BlockedClients},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${BlockedDomainRules},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Enabled}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => DNSServerAccessSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $AllowedClients) {
            throw "invalid value for 'AllowedClients', 'AllowedClients' cannot be null."
        }

        if ($null -eq $BlockKnownScanners) {
            throw "invalid value for 'BlockKnownScanners', 'BlockKnownScanners' cannot be null."
        }

        if ($null -eq $BlockedClients) {
            throw "invalid value for 'BlockedClients', 'BlockedClients' cannot be null."
        }

        if ($null -eq $BlockedDomainRules) {
            throw "invalid value for 'BlockedDomainRules', 'BlockedDomainRules' cannot be null."
        }

        if ($null -eq $Enabled) {
            throw "invalid value for 'Enabled', 'Enabled' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "allowed_clients" = ${AllowedClients}
            "block_known_scanners" = ${BlockKnownScanners}
            "blocked_clients" = ${BlockedClients}
            "blocked_domain_rules" = ${BlockedDomainRules}
            "enabled" = ${Enabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to DNSServerAccessSettings<PSCustomObject>

.DESCRIPTION

Convert from JSON to DNSServerAccessSettings<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

DNSServerAccessSettings<PSCustomObject>
#>
function ConvertFrom-JsonToDNSServerAccessSettings {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => DNSServerAccessSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in DNSServerAccessSettings
        $AllProperties = ("allowed_clients", "block_known_scanners", "blocked_clients", "blocked_domain_rules", "enabled")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'allowed_clients' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "allowed_clients"))) {
            throw "Error! JSON cannot be serialized due to the required property 'allowed_clients' missing."
        } else {
            $AllowedClients = $JsonParameters.PSobject.Properties["allowed_clients"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "block_known_scanners"))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_known_scanners' missing."
        } else {
            $BlockKnownScanners = $JsonParameters.PSobject.Properties["block_known_scanners"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blocked_clients"))) {
            throw "Error! JSON cannot be serialized due to the required property 'blocked_clients' missing."
        } else {
            $BlockedClients = $JsonParameters.PSobject.Properties["blocked_clients"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blocked_domain_rules"))) {
            throw "Error! JSON cannot be serialized due to the required property 'blocked_domain_rules' missing."
        } else {
            $BlockedDomainRules = $JsonParameters.PSobject.Properties["blocked_domain_rules"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'enabled' missing."
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        $PSO = [PSCustomObject]@{
            "allowed_clients" = ${AllowedClients}
            "block_known_scanners" = ${BlockKnownScanners}
            "blocked_clients" = ${BlockedClients}
            "blocked_domain_rules" = ${BlockedDomainRules}
            "enabled" = ${Enabled}
        }

        return $PSO
    }

}

