#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Fields errors

.PARAMETER ErrorCode
No description available.
.PARAMETER Field
Field name
.PARAMETER Message
Error message
.OUTPUTS

FieldError<PSCustomObject>
#>

function Initialize-FieldError {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("BAD_REQUEST", "FIELD_REQUIRED", "FIELD_WRONG_VALUE", "FIELD_REACHED_LIMIT", "UNKNOWN")]
        [PSCustomObject]
        ${ErrorCode},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Field},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Message}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => FieldError' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $ErrorCode) {
            throw "invalid value for 'ErrorCode', 'ErrorCode' cannot be null."
        }

        if ($null -eq $Field) {
            throw "invalid value for 'Field', 'Field' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "error_code" = ${ErrorCode}
            "field" = ${Field}
            "message" = ${Message}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FieldError<PSCustomObject>

.DESCRIPTION

Convert from JSON to FieldError<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FieldError<PSCustomObject>
#>
function ConvertFrom-JsonToFieldError {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => FieldError' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FieldError
        $AllProperties = ("error_code", "field", "message")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'error_code' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "error_code"))) {
            throw "Error! JSON cannot be serialized due to the required property 'error_code' missing."
        } else {
            $ErrorCode = $JsonParameters.PSobject.Properties["error_code"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "field"))) {
            throw "Error! JSON cannot be serialized due to the required property 'field' missing."
        } else {
            $Field = $JsonParameters.PSobject.Properties["field"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "message"))) { #optional property not found
            $Message = $null
        } else {
            $Message = $JsonParameters.PSobject.Properties["message"].value
        }

        $PSO = [PSCustomObject]@{
            "error_code" = ${ErrorCode}
            "field" = ${Field}
            "message" = ${Message}
        }

        return $PSO
    }

}

