#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Filter list

.PARAMETER Categories
Filter categories
.PARAMETER Description
Filter description
.PARAMETER DownloadUrl
Filter download url
.PARAMETER FilterId
Filter ID
.PARAMETER HomepageUrl
Filter homepage url
.PARAMETER Name
Filter name
.PARAMETER RulesCount
Rules count in filter
.PARAMETER SourceUrl
Filter source url
.PARAMETER Tags
Filter tags
.PARAMETER TimeUpdated
Filter last updated time
.OUTPUTS

FilterList<PSCustomObject>
#>

function Initialize-FilterList {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Categories},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Description},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DownloadUrl},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${FilterId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HomepageUrl},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${RulesCount},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SourceUrl},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Tags},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime]
        ${TimeUpdated}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => FilterList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Categories) {
            throw "invalid value for 'Categories', 'Categories' cannot be null."
        }

        if ($null -eq $Description) {
            throw "invalid value for 'Description', 'Description' cannot be null."
        }

        if ($null -eq $DownloadUrl) {
            throw "invalid value for 'DownloadUrl', 'DownloadUrl' cannot be null."
        }

        if ($null -eq $FilterId) {
            throw "invalid value for 'FilterId', 'FilterId' cannot be null."
        }

        if ($null -eq $HomepageUrl) {
            throw "invalid value for 'HomepageUrl', 'HomepageUrl' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $RulesCount) {
            throw "invalid value for 'RulesCount', 'RulesCount' cannot be null."
        }

        if ($null -eq $SourceUrl) {
            throw "invalid value for 'SourceUrl', 'SourceUrl' cannot be null."
        }

        if ($null -eq $Tags) {
            throw "invalid value for 'Tags', 'Tags' cannot be null."
        }

        if ($null -eq $TimeUpdated) {
            throw "invalid value for 'TimeUpdated', 'TimeUpdated' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
            "description" = ${Description}
            "download_url" = ${DownloadUrl}
            "filter_id" = ${FilterId}
            "homepage_url" = ${HomepageUrl}
            "name" = ${Name}
            "rules_count" = ${RulesCount}
            "source_url" = ${SourceUrl}
            "tags" = ${Tags}
            "time_updated" = ${TimeUpdated}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to FilterList<PSCustomObject>

.DESCRIPTION

Convert from JSON to FilterList<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

FilterList<PSCustomObject>
#>
function ConvertFrom-JsonToFilterList {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => FilterList' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in FilterList
        $AllProperties = ("categories", "description", "download_url", "filter_id", "homepage_url", "name", "rules_count", "source_url", "tags", "time_updated")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'categories' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "categories"))) {
            throw "Error! JSON cannot be serialized due to the required property 'categories' missing."
        } else {
            $Categories = $JsonParameters.PSobject.Properties["categories"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "description"))) {
            throw "Error! JSON cannot be serialized due to the required property 'description' missing."
        } else {
            $Description = $JsonParameters.PSobject.Properties["description"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "download_url"))) {
            throw "Error! JSON cannot be serialized due to the required property 'download_url' missing."
        } else {
            $DownloadUrl = $JsonParameters.PSobject.Properties["download_url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "filter_id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'filter_id' missing."
        } else {
            $FilterId = $JsonParameters.PSobject.Properties["filter_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "homepage_url"))) {
            throw "Error! JSON cannot be serialized due to the required property 'homepage_url' missing."
        } else {
            $HomepageUrl = $JsonParameters.PSobject.Properties["homepage_url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rules_count"))) {
            throw "Error! JSON cannot be serialized due to the required property 'rules_count' missing."
        } else {
            $RulesCount = $JsonParameters.PSobject.Properties["rules_count"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "source_url"))) {
            throw "Error! JSON cannot be serialized due to the required property 'source_url' missing."
        } else {
            $SourceUrl = $JsonParameters.PSobject.Properties["source_url"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "tags"))) {
            throw "Error! JSON cannot be serialized due to the required property 'tags' missing."
        } else {
            $Tags = $JsonParameters.PSobject.Properties["tags"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "time_updated"))) {
            throw "Error! JSON cannot be serialized due to the required property 'time_updated' missing."
        } else {
            $TimeUpdated = $JsonParameters.PSobject.Properties["time_updated"].value
        }

        $PSO = [PSCustomObject]@{
            "categories" = ${Categories}
            "description" = ${Description}
            "download_url" = ${DownloadUrl}
            "filter_id" = ${FilterId}
            "homepage_url" = ${HomepageUrl}
            "name" = ${Name}
            "rules_count" = ${RulesCount}
            "source_url" = ${SourceUrl}
            "tags" = ${Tags}
            "time_updated" = ${TimeUpdated}
        }

        return $PSO
    }

}

