#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

IP address info

.PARAMETER IpAddress
IP address string
.PARAMETER Type
No description available.
.OUTPUTS

IpAddress<PSCustomObject>
#>

function Initialize-IpAddress {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${IpAddress},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("V4", "V6")]
        [PSCustomObject]
        ${Type}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => IpAddress' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $IpAddress) {
            throw "invalid value for 'IpAddress', 'IpAddress' cannot be null."
        }

        if ($null -eq $Type) {
            throw "invalid value for 'Type', 'Type' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "ip_address" = ${IpAddress}
            "type" = ${Type}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to IpAddress<PSCustomObject>

.DESCRIPTION

Convert from JSON to IpAddress<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

IpAddress<PSCustomObject>
#>
function ConvertFrom-JsonToIpAddress {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => IpAddress' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in IpAddress
        $AllProperties = ("ip_address", "type")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'ip_address' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "ip_address"))) {
            throw "Error! JSON cannot be serialized due to the required property 'ip_address' missing."
        } else {
            $IpAddress = $JsonParameters.PSobject.Properties["ip_address"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'type' missing."
        } else {
            $Type = $JsonParameters.PSobject.Properties["type"].value
        }

        $PSO = [PSCustomObject]@{
            "ip_address" = ${IpAddress}
            "type" = ${Type}
        }

        return $PSO
    }

}

