#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Pagination

.PARAMETER Current
Is current page
.PARAMETER PageCursor
Pagination cursor
.PARAMETER PageNumber
Page number
.OUTPUTS

Page<PSCustomObject>
#>

function Initialize-Page {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Current},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${PageCursor},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${PageNumber}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => Page' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Current) {
            throw "invalid value for 'Current', 'Current' cannot be null."
        }

        if ($null -eq $PageCursor) {
            throw "invalid value for 'PageCursor', 'PageCursor' cannot be null."
        }

        if ($null -eq $PageNumber) {
            throw "invalid value for 'PageNumber', 'PageNumber' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "current" = ${Current}
            "page_cursor" = ${PageCursor}
            "page_number" = ${PageNumber}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Page<PSCustomObject>

.DESCRIPTION

Convert from JSON to Page<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Page<PSCustomObject>
#>
function ConvertFrom-JsonToPage {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => Page' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in Page
        $AllProperties = ("current", "page_cursor", "page_number")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'current' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "current"))) {
            throw "Error! JSON cannot be serialized due to the required property 'current' missing."
        } else {
            $Current = $JsonParameters.PSobject.Properties["current"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "page_cursor"))) {
            throw "Error! JSON cannot be serialized due to the required property 'page_cursor' missing."
        } else {
            $PageCursor = $JsonParameters.PSobject.Properties["page_cursor"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "page_number"))) {
            throw "Error! JSON cannot be serialized due to the required property 'page_number' missing."
        } else {
            $PageNumber = $JsonParameters.PSobject.Properties["page_number"].value
        }

        $PSO = [PSCustomObject]@{
            "current" = ${Current}
            "page_cursor" = ${PageCursor}
            "page_number" = ${PageNumber}
        }

        return $PSO
    }

}

