#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Parental control settings

.PARAMETER BlockAdultWebsitesEnabled
Disable porno content
.PARAMETER BlockedServices
List of services with restricted access
.PARAMETER Enabled
Is parental control enabled or not
.PARAMETER EnginesSafeSearchEnabled
Enforces safe search for some search engines
.PARAMETER ScreenTimeSchedule
No description available.
.PARAMETER YoutubeSafeSearchEnabled
Enforces safe search on YouTube
.OUTPUTS

ParentalControlSettings<PSCustomObject>
#>

function Initialize-ParentalControlSettings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${BlockAdultWebsitesEnabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${BlockedServices},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Enabled},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${EnginesSafeSearchEnabled},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ScreenTimeSchedule},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${YoutubeSafeSearchEnabled}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => ParentalControlSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $BlockAdultWebsitesEnabled) {
            throw "invalid value for 'BlockAdultWebsitesEnabled', 'BlockAdultWebsitesEnabled' cannot be null."
        }

        if ($null -eq $BlockedServices) {
            throw "invalid value for 'BlockedServices', 'BlockedServices' cannot be null."
        }

        if ($null -eq $Enabled) {
            throw "invalid value for 'Enabled', 'Enabled' cannot be null."
        }

        if ($null -eq $EnginesSafeSearchEnabled) {
            throw "invalid value for 'EnginesSafeSearchEnabled', 'EnginesSafeSearchEnabled' cannot be null."
        }

        if ($null -eq $ScreenTimeSchedule) {
            throw "invalid value for 'ScreenTimeSchedule', 'ScreenTimeSchedule' cannot be null."
        }

        if ($null -eq $YoutubeSafeSearchEnabled) {
            throw "invalid value for 'YoutubeSafeSearchEnabled', 'YoutubeSafeSearchEnabled' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "block_adult_websites_enabled" = ${BlockAdultWebsitesEnabled}
            "blocked_services" = ${BlockedServices}
            "enabled" = ${Enabled}
            "engines_safe_search_enabled" = ${EnginesSafeSearchEnabled}
            "screen_time_schedule" = ${ScreenTimeSchedule}
            "youtube_safe_search_enabled" = ${YoutubeSafeSearchEnabled}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ParentalControlSettings<PSCustomObject>

.DESCRIPTION

Convert from JSON to ParentalControlSettings<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ParentalControlSettings<PSCustomObject>
#>
function ConvertFrom-JsonToParentalControlSettings {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => ParentalControlSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ParentalControlSettings
        $AllProperties = ("block_adult_websites_enabled", "blocked_services", "enabled", "engines_safe_search_enabled", "screen_time_schedule", "youtube_safe_search_enabled")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'block_adult_websites_enabled' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "block_adult_websites_enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'block_adult_websites_enabled' missing."
        } else {
            $BlockAdultWebsitesEnabled = $JsonParameters.PSobject.Properties["block_adult_websites_enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blocked_services"))) {
            throw "Error! JSON cannot be serialized due to the required property 'blocked_services' missing."
        } else {
            $BlockedServices = $JsonParameters.PSobject.Properties["blocked_services"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'enabled' missing."
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "engines_safe_search_enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'engines_safe_search_enabled' missing."
        } else {
            $EnginesSafeSearchEnabled = $JsonParameters.PSobject.Properties["engines_safe_search_enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "screen_time_schedule"))) {
            throw "Error! JSON cannot be serialized due to the required property 'screen_time_schedule' missing."
        } else {
            $ScreenTimeSchedule = $JsonParameters.PSobject.Properties["screen_time_schedule"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "youtube_safe_search_enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'youtube_safe_search_enabled' missing."
        } else {
            $YoutubeSafeSearchEnabled = $JsonParameters.PSobject.Properties["youtube_safe_search_enabled"].value
        }

        $PSO = [PSCustomObject]@{
            "block_adult_websites_enabled" = ${BlockAdultWebsitesEnabled}
            "blocked_services" = ${BlockedServices}
            "enabled" = ${Enabled}
            "engines_safe_search_enabled" = ${EnginesSafeSearchEnabled}
            "screen_time_schedule" = ${ScreenTimeSchedule}
            "youtube_safe_search_enabled" = ${YoutubeSafeSearchEnabled}
        }

        return $PSO
    }

}

