#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Query log item info

.PARAMETER Asn
AS number
.PARAMETER CategoryType
No description available.
.PARAMETER ClientCountry
Client country code
.PARAMETER CompanyId
Company ID
.PARAMETER DeviceId
Device ID
.PARAMETER DnsProtoType
No description available.
.PARAMETER DnsRequestType
DNS protocol request type
.PARAMETER DnsResponseType
No description available.
.PARAMETER Dnssec
Requested with DNSSec
.PARAMETER Domain
Domain name
.PARAMETER FilteringInfo
No description available.
.PARAMETER Network
Network name
.PARAMETER ResponseCountry
Response country code
.PARAMETER TimeIso
Event time
.PARAMETER TimeMillis
Event time
.OUTPUTS

QueryLogItem<PSCustomObject>
#>

function Initialize-QueryLogItem {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Int32]]
        ${Asn},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("ADS", "TRACKERS", "SOCIAL_MEDIA", "CDN", "OTHERS")]
        [PSCustomObject]
        ${CategoryType},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ClientCountry},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${CompanyId},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DeviceId},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${DnsProtoType},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DnsRequestType},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("RcodeSuccess", "RcodeFormatError", "RcodeServerFailure", "RcodeNameError", "RcodeNotImplemented", "RcodeRefused", "RcodeYXDomain", "RcodeYXRrset", "RcodeNXRrset", "RcodeNotAuth", "RcodeNotZone", "RcodeBadSig", "RcodeBadVers", "RcodeBadKey", "RcodeBadTime", "RcodeBadMode", "RcodeBadName", "RcodeBadAlg", "RcodeBadTrunc", "RcodeBadCookie")]
        [PSCustomObject]
        ${DnsResponseType},
        [Parameter(Position = 8, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Dnssec},
        [Parameter(Position = 9, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Domain},
        [Parameter(Position = 10, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${FilteringInfo},
        [Parameter(Position = 11, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Network},
        [Parameter(Position = 12, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ResponseCountry},
        [Parameter(Position = 13, ValueFromPipelineByPropertyName = $true)]
        [System.DateTime]
        ${TimeIso},
        [Parameter(Position = 14, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${TimeMillis}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => QueryLogItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $CategoryType) {
            throw "invalid value for 'CategoryType', 'CategoryType' cannot be null."
        }

        if ($null -eq $CompanyId) {
            throw "invalid value for 'CompanyId', 'CompanyId' cannot be null."
        }

        if ($null -eq $Dnssec) {
            throw "invalid value for 'Dnssec', 'Dnssec' cannot be null."
        }

        if ($null -eq $Domain) {
            throw "invalid value for 'Domain', 'Domain' cannot be null."
        }

        if ($null -eq $FilteringInfo) {
            throw "invalid value for 'FilteringInfo', 'FilteringInfo' cannot be null."
        }

        if ($null -eq $TimeIso) {
            throw "invalid value for 'TimeIso', 'TimeIso' cannot be null."
        }

        if ($null -eq $TimeMillis) {
            throw "invalid value for 'TimeMillis', 'TimeMillis' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "asn" = ${Asn}
            "category_type" = ${CategoryType}
            "client_country" = ${ClientCountry}
            "company_id" = ${CompanyId}
            "device_id" = ${DeviceId}
            "dns_proto_type" = ${DnsProtoType}
            "dns_request_type" = ${DnsRequestType}
            "dns_response_type" = ${DnsResponseType}
            "dnssec" = ${Dnssec}
            "domain" = ${Domain}
            "filtering_info" = ${FilteringInfo}
            "network" = ${Network}
            "response_country" = ${ResponseCountry}
            "time_iso" = ${TimeIso}
            "time_millis" = ${TimeMillis}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to QueryLogItem<PSCustomObject>

.DESCRIPTION

Convert from JSON to QueryLogItem<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

QueryLogItem<PSCustomObject>
#>
function ConvertFrom-JsonToQueryLogItem {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => QueryLogItem' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in QueryLogItem
        $AllProperties = ("asn", "category_type", "client_country", "company_id", "device_id", "dns_proto_type", "dns_request_type", "dns_response_type", "dnssec", "domain", "filtering_info", "network", "response_country", "time_iso", "time_millis")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'category_type' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "category_type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'category_type' missing."
        } else {
            $CategoryType = $JsonParameters.PSobject.Properties["category_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "company_id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'company_id' missing."
        } else {
            $CompanyId = $JsonParameters.PSobject.Properties["company_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dnssec"))) {
            throw "Error! JSON cannot be serialized due to the required property 'dnssec' missing."
        } else {
            $Dnssec = $JsonParameters.PSobject.Properties["dnssec"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "domain"))) {
            throw "Error! JSON cannot be serialized due to the required property 'domain' missing."
        } else {
            $Domain = $JsonParameters.PSobject.Properties["domain"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "filtering_info"))) {
            throw "Error! JSON cannot be serialized due to the required property 'filtering_info' missing."
        } else {
            $FilteringInfo = $JsonParameters.PSobject.Properties["filtering_info"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "time_iso"))) {
            throw "Error! JSON cannot be serialized due to the required property 'time_iso' missing."
        } else {
            $TimeIso = $JsonParameters.PSobject.Properties["time_iso"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "time_millis"))) {
            throw "Error! JSON cannot be serialized due to the required property 'time_millis' missing."
        } else {
            $TimeMillis = $JsonParameters.PSobject.Properties["time_millis"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "asn"))) { #optional property not found
            $Asn = $null
        } else {
            $Asn = $JsonParameters.PSobject.Properties["asn"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "client_country"))) { #optional property not found
            $ClientCountry = $null
        } else {
            $ClientCountry = $JsonParameters.PSobject.Properties["client_country"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "device_id"))) { #optional property not found
            $DeviceId = $null
        } else {
            $DeviceId = $JsonParameters.PSobject.Properties["device_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dns_proto_type"))) { #optional property not found
            $DnsProtoType = $null
        } else {
            $DnsProtoType = $JsonParameters.PSobject.Properties["dns_proto_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dns_request_type"))) { #optional property not found
            $DnsRequestType = $null
        } else {
            $DnsRequestType = $JsonParameters.PSobject.Properties["dns_request_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "dns_response_type"))) { #optional property not found
            $DnsResponseType = $null
        } else {
            $DnsResponseType = $JsonParameters.PSobject.Properties["dns_response_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "network"))) { #optional property not found
            $Network = $null
        } else {
            $Network = $JsonParameters.PSobject.Properties["network"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "response_country"))) { #optional property not found
            $ResponseCountry = $null
        } else {
            $ResponseCountry = $JsonParameters.PSobject.Properties["response_country"].value
        }

        $PSO = [PSCustomObject]@{
            "asn" = ${Asn}
            "category_type" = ${CategoryType}
            "client_country" = ${ClientCountry}
            "company_id" = ${CompanyId}
            "device_id" = ${DeviceId}
            "dns_proto_type" = ${DnsProtoType}
            "dns_request_type" = ${DnsRequestType}
            "dns_response_type" = ${DnsResponseType}
            "dnssec" = ${Dnssec}
            "domain" = ${Domain}
            "filtering_info" = ${FilteringInfo}
            "network" = ${Network}
            "response_country" = ${ResponseCountry}
            "time_iso" = ${TimeIso}
            "time_millis" = ${TimeMillis}
        }

        return $PSO
    }

}

