#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Overall / blocked / companies queries count

.PARAMETER Blocked
Blocked queries count
.PARAMETER Companies
Companies count
.PARAMETER Queries
Overall queries count
.OUTPUTS

QueriesStats<PSCustomObject>
#>

function Initialize-QueriesStats {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${Blocked},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${Companies},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${Queries}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => QueriesStats' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Blocked) {
            throw "invalid value for 'Blocked', 'Blocked' cannot be null."
        }

        if ($null -eq $Companies) {
            throw "invalid value for 'Companies', 'Companies' cannot be null."
        }

        if ($null -eq $Queries) {
            throw "invalid value for 'Queries', 'Queries' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "blocked" = ${Blocked}
            "companies" = ${Companies}
            "queries" = ${Queries}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to QueriesStats<PSCustomObject>

.DESCRIPTION

Convert from JSON to QueriesStats<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

QueriesStats<PSCustomObject>
#>
function ConvertFrom-JsonToQueriesStats {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => QueriesStats' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in QueriesStats
        $AllProperties = ("blocked", "companies", "queries")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'blocked' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blocked"))) {
            throw "Error! JSON cannot be serialized due to the required property 'blocked' missing."
        } else {
            $Blocked = $JsonParameters.PSobject.Properties["blocked"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "companies"))) {
            throw "Error! JSON cannot be serialized due to the required property 'companies' missing."
        } else {
            $Companies = $JsonParameters.PSobject.Properties["companies"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "queries"))) {
            throw "Error! JSON cannot be serialized due to the required property 'queries' missing."
        } else {
            $Queries = $JsonParameters.PSobject.Properties["queries"].value
        }

        $PSO = [PSCustomObject]@{
            "blocked" = ${Blocked}
            "companies" = ${Companies}
            "queries" = ${Queries}
        }

        return $PSO
    }

}

