#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum RegularDnsProtoType.

.DESCRIPTION

Regular DNS proto type. Scheduled for removal: PLAIN_TCP, PLAIN_UDP
#>

enum RegularDnsProtoType {
    # enum value: "DNS"
    DNS
    # enum value: "PLAIN_TCP"
    PLAIN_TCP
    # enum value: "PLAIN_UDP"
    PLAIN_UDP
}

