#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

Describes a schedule for day

.PARAMETER DayOfWeek
No description available.
.PARAMETER Enabled
Shows enabled/disabled day
.PARAMETER FromTime
No description available.
.PARAMETER ToTime
No description available.
.OUTPUTS

ScheduleDay<PSCustomObject>
#>

function Initialize-ScheduleDay {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [ValidateSet("MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY")]
        [PSCustomObject]
        ${DayOfWeek},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Enabled},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${FromTime},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${ToTime}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => ScheduleDay' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $DayOfWeek) {
            throw "invalid value for 'DayOfWeek', 'DayOfWeek' cannot be null."
        }

        if ($null -eq $Enabled) {
            throw "invalid value for 'Enabled', 'Enabled' cannot be null."
        }

        if ($null -eq $FromTime) {
            throw "invalid value for 'FromTime', 'FromTime' cannot be null."
        }

        if ($null -eq $ToTime) {
            throw "invalid value for 'ToTime', 'ToTime' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "day_of_week" = ${DayOfWeek}
            "enabled" = ${Enabled}
            "from_time" = ${FromTime}
            "to_time" = ${ToTime}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ScheduleDay<PSCustomObject>

.DESCRIPTION

Convert from JSON to ScheduleDay<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ScheduleDay<PSCustomObject>
#>
function ConvertFrom-JsonToScheduleDay {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => ScheduleDay' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in ScheduleDay
        $AllProperties = ("day_of_week", "enabled", "from_time", "to_time")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'day_of_week' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "day_of_week"))) {
            throw "Error! JSON cannot be serialized due to the required property 'day_of_week' missing."
        } else {
            $DayOfWeek = $JsonParameters.PSobject.Properties["day_of_week"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'enabled' missing."
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "from_time"))) {
            throw "Error! JSON cannot be serialized due to the required property 'from_time' missing."
        } else {
            $FromTime = $JsonParameters.PSobject.Properties["from_time"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "to_time"))) {
            throw "Error! JSON cannot be serialized due to the required property 'to_time' missing."
        } else {
            $ToTime = $JsonParameters.PSobject.Properties["to_time"].value
        }

        $PSO = [PSCustomObject]@{
            "day_of_week" = ${DayOfWeek}
            "enabled" = ${Enabled}
            "from_time" = ${FromTime}
            "to_time" = ${ToTime}
        }

        return $PSO
    }

}

