#
# AdGuard DNS API
# DNS API documentation
# Version: 1.11
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

User rules

.PARAMETER Enabled
The flag that all rules are on or off
.PARAMETER Rules
List of rules
.PARAMETER RulesCount
Rules count in user list
.OUTPUTS

UserRulesSettings<PSCustomObject>
#>

function Initialize-UserRulesSettings {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [Boolean]
        ${Enabled},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String[]]
        ${Rules},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [Int32]
        ${RulesCount}
    )

    Process {
        'Creating PSCustomObject: PSAdGuardDNS => UserRulesSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Enabled) {
            throw "invalid value for 'Enabled', 'Enabled' cannot be null."
        }

        if ($null -eq $Rules) {
            throw "invalid value for 'Rules', 'Rules' cannot be null."
        }

        if ($null -eq $RulesCount) {
            throw "invalid value for 'RulesCount', 'RulesCount' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "rules" = ${Rules}
            "rules_count" = ${RulesCount}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to UserRulesSettings<PSCustomObject>

.DESCRIPTION

Convert from JSON to UserRulesSettings<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

UserRulesSettings<PSCustomObject>
#>
function ConvertFrom-JsonToUserRulesSettings {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSAdGuardDNS => UserRulesSettings' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in UserRulesSettings
        $AllProperties = ("enabled", "rules", "rules_count")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'enabled' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "enabled"))) {
            throw "Error! JSON cannot be serialized due to the required property 'enabled' missing."
        } else {
            $Enabled = $JsonParameters.PSobject.Properties["enabled"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rules"))) {
            throw "Error! JSON cannot be serialized due to the required property 'rules' missing."
        } else {
            $Rules = $JsonParameters.PSobject.Properties["rules"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "rules_count"))) {
            throw "Error! JSON cannot be serialized due to the required property 'rules_count' missing."
        } else {
            $RulesCount = $JsonParameters.PSobject.Properties["rules_count"].value
        }

        $PSO = [PSCustomObject]@{
            "enabled" = ${Enabled}
            "rules" = ${Rules}
            "rules_count" = ${RulesCount}
        }

        return $PSO
    }

}

