/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for passing parameters to the method [`access_token`]
#[derive(Clone, Debug)]
pub struct AccessTokenParams {
    /// Two-Factor authentication token
    pub mfa_token: Option<String>,
    /// Account password
    pub password: Option<String>,
    /// Refresh Token using which a new access token has to be generated
    pub refresh_token: Option<String>,
    /// Account email
    pub username: Option<String>,
}

/// struct for passing parameters to the method [`revoke_token`]
#[derive(Clone, Debug)]
pub struct RevokeTokenParams {
    /// Refresh Token
    pub refresh_token: String,
}

/// struct for typed errors of method [`access_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AccessTokenError {
    Status400(models::AccessTokenResponse),
    Status401(models::AccessTokenErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`revoke_token`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RevokeTokenError {
    UnknownValue(serde_json::Value),
}

pub async fn access_token(
    configuration: &configuration::Configuration,
    params: AccessTokenParams,
) -> Result<models::AccessTokenResponse, Error<AccessTokenError>> {
    let uri_str = format!("{}/oapi/v1/oauth_token", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    let mut multipart_form_params = std::collections::HashMap::new();
    if let Some(param_value) = params.mfa_token {
        multipart_form_params.insert("mfa_token", param_value.to_string());
    }
    if let Some(param_value) = params.password {
        multipart_form_params.insert("password", param_value.to_string());
    }
    if let Some(param_value) = params.refresh_token {
        multipart_form_params.insert("refresh_token", param_value.to_string());
    }
    if let Some(param_value) = params.username {
        multipart_form_params.insert("username", param_value.to_string());
    }
    req_builder = req_builder.form(&multipart_form_params);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AccessTokenResponse`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `models::AccessTokenResponse`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<AccessTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

pub async fn revoke_token(
    configuration: &configuration::Configuration,
    params: RevokeTokenParams,
) -> Result<(), Error<RevokeTokenError>> {
    let uri_str = format!("{}/oapi/v1/revoke_token", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("refresh_token", &params.refresh_token.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<RevokeTokenError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
