/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using AdGuard.ApiClient.Client;
using AdGuard.ApiClient.Api;
using AdGuard.ApiClient.Model;

namespace AdGuard.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing DNSServersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DNSServersApiTests : IDisposable
    {
        private DNSServersApi instance;

        public DNSServersApiTests()
        {
            instance = new DNSServersApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DNSServersApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            Assert.IsType<DNSServersApi>(instance);
        }

        /// <summary>
        /// Test CreateDNSServer
        /// </summary>
        [Fact]
        public void CreateDNSServerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //DNSServerCreate dNSServerCreate = null;
            //var response = instance.CreateDNSServer(dNSServerCreate);
            //Assert.IsType<DNSServer>(response);
        }

        /// <summary>
        /// Test ListDNSServers
        /// </summary>
        [Fact]
        public void ListDNSServersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListDNSServers();
            //Assert.IsType<List<DNSServer>>(response);
        }

        #region UpdateDNSServerSettings Tests

        /// <summary>
        /// Test UpdateDNSServerSettings with null server ID throws exception
        /// </summary>
        [Fact]
        public void UpdateDNSServerSettings_WithNullServerId_ThrowsApiException()
        {
            // Arrange
            var settingsUpdate = new DNSServerSettingsUpdate();

            // Act & Assert
            var exception = Assert.Throws<ApiException>(
                () => instance.UpdateDNSServerSettings(null!, settingsUpdate));

            Assert.Equal(400, exception.ErrorCode);
            Assert.Contains("dnsServerId", exception.Message);
        }

        /// <summary>
        /// Test UpdateDNSServerSettings with null settings update throws exception
        /// </summary>
        [Fact]
        public void UpdateDNSServerSettings_WithNullSettingsUpdate_ThrowsApiException()
        {
            // Arrange
            var serverId = "test-server-id";

            // Act & Assert
            var exception = Assert.Throws<ApiException>(
                () => instance.UpdateDNSServerSettings(serverId, null!));

            Assert.Equal(400, exception.ErrorCode);
            Assert.Contains("dnsServerSettingsUpdate", exception.Message);
        }

        /// <summary>
        /// Test UpdateDNSServerSettingsAsync with null server ID throws exception
        /// </summary>
        [Fact]
        public async void UpdateDNSServerSettingsAsync_WithNullServerId_ThrowsApiException()
        {
            // Arrange
            var settingsUpdate = new DNSServerSettingsUpdate();

            // Act & Assert
            var exception = await Assert.ThrowsAsync<ApiException>(
                () => instance.UpdateDNSServerSettingsAsync(null!, settingsUpdate));

            Assert.Equal(400, exception.ErrorCode);
            Assert.Contains("dnsServerId", exception.Message);
        }

        /// <summary>
        /// Test UpdateDNSServerSettingsAsync with null settings update throws exception
        /// </summary>
        [Fact]
        public async void UpdateDNSServerSettingsAsync_WithNullSettingsUpdate_ThrowsApiException()
        {
            // Arrange
            var serverId = "test-server-id";

            // Act & Assert
            var exception = await Assert.ThrowsAsync<ApiException>(
                () => instance.UpdateDNSServerSettingsAsync(serverId, null!));

            Assert.Equal(400, exception.ErrorCode);
            Assert.Contains("dnsServerSettingsUpdate", exception.Message);
        }

        /// <summary>
        /// Test UpdateDNSServerSettings method exists and is accessible
        /// </summary>
        [Fact]
        public void UpdateDNSServerSettings_MethodExists()
        {
            // Arrange
            var methodInfo = typeof(DNSServersApi).GetMethod(
                "UpdateDNSServerSettings",
                new[] { typeof(string), typeof(DNSServerSettingsUpdate) });

            // Assert
            Assert.NotNull(methodInfo);
            Assert.Equal(typeof(void), methodInfo.ReturnType);
        }

        /// <summary>
        /// Test UpdateDNSServerSettingsAsync method exists and is accessible
        /// </summary>
        [Fact]
        public void UpdateDNSServerSettingsAsync_MethodExists()
        {
            // Arrange
            var methodInfo = typeof(DNSServersApi).GetMethod(
                "UpdateDNSServerSettingsAsync",
                new[] { typeof(string), typeof(DNSServerSettingsUpdate), typeof(System.Threading.CancellationToken) });

            // Assert
            Assert.NotNull(methodInfo);
            Assert.True(methodInfo.ReturnType.IsAssignableTo(typeof(System.Threading.Tasks.Task)));
        }

        /// <summary>
        /// Test UpdateDNSServerSettingsWithHttpInfo method exists
        /// </summary>
        [Fact]
        public void UpdateDNSServerSettingsWithHttpInfo_MethodExists()
        {
            // Arrange
            var methodInfo = typeof(DNSServersApi).GetMethod(
                "UpdateDNSServerSettingsWithHttpInfo",
                new[] { typeof(string), typeof(DNSServerSettingsUpdate) });

            // Assert
            Assert.NotNull(methodInfo);
        }

        /// <summary>
        /// Test that the API interface includes UpdateDNSServerSettings
        /// </summary>
        [Fact]
        public void IDNSServersApi_IncludesUpdateDNSServerSettings()
        {
            // Assert
            Assert.True(instance is IDNSServersApi);

            var syncInterface = typeof(IDNSServersApiSync);
            var method = syncInterface.GetMethod(
                "UpdateDNSServerSettings",
                new[] { typeof(string), typeof(DNSServerSettingsUpdate) });

            Assert.NotNull(method);
        }

        /// <summary>
        /// Test that the async API interface includes UpdateDNSServerSettingsAsync
        /// </summary>
        [Fact]
        public void IDNSServersApiAsync_IncludesUpdateDNSServerSettingsAsync()
        {
            // Assert
            var asyncInterface = typeof(IDNSServersApiAsync);
            var method = asyncInterface.GetMethod(
                "UpdateDNSServerSettingsAsync",
                new[] { typeof(string), typeof(DNSServerSettingsUpdate), typeof(System.Threading.CancellationToken) });

            Assert.NotNull(method);
        }

        #endregion
    }
}
