/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// Device
    /// </summary>
    [DataContract(Name = "Device")]
    public partial class Device : IValidatableObject
    {
        /// <summary>
        /// Defines DeviceType
        /// </summary>
        [JsonConverter(typeof(JsonStringEnumConverter))]
        public enum DeviceTypeEnum
        {
            /// <summary>
            /// Enum WINDOWS for value: WINDOWS
            /// </summary>
            [EnumMember(Value = "WINDOWS")]
            WINDOWS = 1,

            /// <summary>
            /// Enum ANDROID for value: ANDROID
            /// </summary>
            [EnumMember(Value = "ANDROID")]
            ANDROID = 2,

            /// <summary>
            /// Enum MAC for value: MAC
            /// </summary>
            [EnumMember(Value = "MAC")]
            MAC = 3,

            /// <summary>
            /// Enum IOS for value: IOS
            /// </summary>
            [EnumMember(Value = "IOS")]
            IOS = 4,

            /// <summary>
            /// Enum LINUX for value: LINUX
            /// </summary>
            [EnumMember(Value = "LINUX")]
            LINUX = 5,

            /// <summary>
            /// Enum ROUTER for value: ROUTER
            /// </summary>
            [EnumMember(Value = "ROUTER")]
            ROUTER = 6,

            /// <summary>
            /// Enum SMARTTV for value: SMART_TV
            /// </summary>
            [EnumMember(Value = "SMART_TV")]
            SMARTTV = 7,

            /// <summary>
            /// Enum GAMECONSOLE for value: GAME_CONSOLE
            /// </summary>
            [EnumMember(Value = "GAME_CONSOLE")]
            GAMECONSOLE = 8,

            /// <summary>
            /// Enum UNKNOWN for value: UNKNOWN
            /// </summary>
            [EnumMember(Value = "UNKNOWN")]
            UNKNOWN = 9
        }


        /// <summary>
        /// Gets or Sets DeviceType
        /// </summary>
        [DataMember(Name = "device_type", IsRequired = true, EmitDefaultValue = true)]
        public DeviceTypeEnum DeviceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Device" /> class.
        /// </summary>
        [JsonConstructor]
        protected Device() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Device" /> class.
        /// </summary>
        /// <param name="deviceType">deviceType (required).</param>
        /// <param name="dnsAddresses">dnsAddresses (required).</param>
        /// <param name="dnsServerId">dnsServerId (required).</param>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="settings">settings (required).</param>
        public Device(DeviceTypeEnum deviceType = default, Object dnsAddresses = default, string dnsServerId = default, string id = default, string name = default, Object settings = default)
        {
            this.DeviceType = deviceType;
            // to ensure "dnsAddresses" is required (not null)
            if (dnsAddresses == null)
            {
                throw new ArgumentNullException("dnsAddresses is a required property for Device and cannot be null");
            }
            this.DnsAddresses = dnsAddresses;
            // to ensure "dnsServerId" is required (not null)
            if (dnsServerId == null)
            {
                throw new ArgumentNullException("dnsServerId is a required property for Device and cannot be null");
            }
            this.DnsServerId = dnsServerId;
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for Device and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for Device and cannot be null");
            }
            this.Name = name;
            // to ensure "settings" is required (not null)
            if (settings == null)
            {
                throw new ArgumentNullException("settings is a required property for Device and cannot be null");
            }
            this.Settings = settings;
        }

        /// <summary>
        /// Gets or Sets DnsAddresses
        /// </summary>
        [DataMember(Name = "dns_addresses", IsRequired = true, EmitDefaultValue = true)]
        public Object DnsAddresses { get; set; }

        /// <summary>
        /// Gets or Sets DnsServerId
        /// </summary>
        [DataMember(Name = "dns_server_id", IsRequired = true, EmitDefaultValue = true)]
        public string DnsServerId { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Settings
        /// </summary>
        [DataMember(Name = "settings", IsRequired = true, EmitDefaultValue = true)]
        public Object Settings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Device {\n");
            sb.Append("  DeviceType: ").Append(DeviceType).Append("\n");
            sb.Append("  DnsAddresses: ").Append(DnsAddresses).Append("\n");
            sb.Append("  DnsServerId: ").Append(DnsServerId).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Settings: ").Append(Settings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
