/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using FileParameter = AdGuard.ApiClient.Client.FileParameter;
using OpenAPIDateConverter = AdGuard.ApiClient.Client.OpenAPIDateConverter;

namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// DNS server settings update action.
    /// </summary>
    [DataContract(Name = "DNSServerSettingsUpdate")]
    public partial class DNSServerSettingsUpdate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DNSServerSettingsUpdate" /> class.
        /// </summary>
        /// <param name="userRulesSettings">User rules settings update.</param>
        public DNSServerSettingsUpdate(UserRulesSettingsUpdate userRulesSettings = null)
        {
            this.UserRulesSettings = userRulesSettings;
        }

        /// <summary>
        /// Gets or Sets UserRulesSettings
        /// </summary>
        [DataMember(Name = "user_rules_settings", EmitDefaultValue = false)]
        public UserRulesSettingsUpdate UserRulesSettings { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DNSServerSettingsUpdate {\n");
            sb.Append("  UserRulesSettings: ").Append(UserRulesSettings).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
