/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


namespace AdGuard.ApiClient.Model
{
    /// <summary>
    /// FilterList
    /// </summary>
    [DataContract(Name = "FilterList")]
    public partial class FilterList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FilterList" /> class.
        /// </summary>
        /// <param name="filterId">filterId.</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        public FilterList(string filterId = default, string name = default, string description = default)
        {
            this.FilterId = filterId;
            this.Name = name;
            this.Description = description;
        }

        /// <summary>
        /// Gets or Sets FilterId
        /// </summary>
        [DataMember(Name = "filter_id", EmitDefaultValue = false)]
        public string FilterId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FilterList {\n");
            sb.Append("  FilterId: ").Append(FilterId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
