/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */



// uncomment below to import models
//using AdGuard.ApiClient.Model;

namespace AdGuard.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing FilterListsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FilterListsApiTests : IDisposable
    {
        private FilterListsApi instance;

        public FilterListsApiTests()
        {
            instance = new FilterListsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilterListsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FilterListsApi
            //Assert.IsType<FilterListsApi>(instance);
        }

        /// <summary>
        /// Test ListFilterLists
        /// </summary>
        [Fact]
        public void ListFilterListsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListFilterLists();
            //Assert.IsType<List<FilterList>>(response);
        }
    }
}
