/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using AdGuard.ApiClient.Client;
using AdGuard.ApiClient.Api;
// uncomment below to import models
//using AdGuard.ApiClient.Model;

namespace AdGuard.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing QueryLogApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class QueryLogApiTests : IDisposable
    {
        private QueryLogApi instance;

        public QueryLogApiTests()
        {
            instance = new QueryLogApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of QueryLogApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' QueryLogApi
            //Assert.IsType<QueryLogApi>(instance);
        }

        /// <summary>
        /// Test ClearQueryLog
        /// </summary>
        [Fact]
        public void ClearQueryLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ClearQueryLog();
        }

        /// <summary>
        /// Test GetQueryLog
        /// </summary>
        [Fact]
        public void GetQueryLogTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long timeFromMillis = null;
            //long timeToMillis = null;
            //var response = instance.GetQueryLog(timeFromMillis, timeToMillis);
            //Assert.IsType<QueryLogResponse>(response);
        }
    }
}
