/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;

namespace AdGuard.ApiClient.Helpers
{
    /// <summary>
    /// Extension methods for DateTime conversions to Unix milliseconds (as used by AdGuard DNS API)
    /// </summary>
    public static class DateTimeExtensions
    {
        private static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        /// <summary>
        /// Converts a DateTime to Unix milliseconds timestamp
        /// </summary>
        /// <param name="dateTime">DateTime to convert</param>
        /// <returns>Unix milliseconds timestamp</returns>
        public static long ToUnixMilliseconds(this DateTime dateTime)
        {
            var utcDateTime = dateTime.ToUniversalTime();
            return (long)(utcDateTime - UnixEpoch).TotalMilliseconds;
        }

        /// <summary>
        /// Converts a DateTimeOffset to Unix milliseconds timestamp
        /// </summary>
        /// <param name="dateTimeOffset">DateTimeOffset to convert</param>
        /// <returns>Unix milliseconds timestamp</returns>
        public static long ToUnixMilliseconds(this DateTimeOffset dateTimeOffset)
        {
            return dateTimeOffset.ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Converts Unix milliseconds timestamp to DateTime (UTC)
        /// </summary>
        /// <param name="unixMilliseconds">Unix milliseconds timestamp</param>
        /// <returns>DateTime in UTC</returns>
        public static DateTime FromUnixMilliseconds(long unixMilliseconds)
        {
            return UnixEpoch.AddMilliseconds(unixMilliseconds);
        }

        /// <summary>
        /// Converts Unix milliseconds timestamp to DateTimeOffset (UTC)
        /// </summary>
        /// <param name="unixMilliseconds">Unix milliseconds timestamp</param>
        /// <returns>DateTimeOffset in UTC</returns>
        public static DateTimeOffset FromUnixMillisecondsToOffset(long unixMilliseconds)
        {
            return DateTimeOffset.FromUnixTimeMilliseconds(unixMilliseconds);
        }

        /// <summary>
        /// Gets Unix milliseconds for the current UTC time
        /// </summary>
        /// <returns>Current Unix milliseconds timestamp</returns>
        public static long Now()
        {
            return DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for a time relative to now
        /// </summary>
        /// <param name="timeSpan">TimeSpan to add to current time</param>
        /// <returns>Unix milliseconds timestamp for the future/past time</returns>
        public static long FromNow(TimeSpan timeSpan)
        {
            return DateTimeOffset.UtcNow.Add(timeSpan).ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for X days ago
        /// </summary>
        /// <param name="days">Number of days ago</param>
        /// <returns>Unix milliseconds timestamp for days ago</returns>
        public static long DaysAgo(int days)
        {
            return DateTimeOffset.UtcNow.AddDays(-Math.Abs(days)).ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for X hours ago
        /// </summary>
        /// <param name="hours">Number of hours ago</param>
        /// <returns>Unix milliseconds timestamp for hours ago</returns>
        public static long HoursAgo(int hours)
        {
            return DateTimeOffset.UtcNow.AddHours(-Math.Abs(hours)).ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for the start of today (UTC)
        /// </summary>
        /// <returns>Unix milliseconds timestamp for start of today</returns>
        public static long StartOfToday()
        {
            var today = DateTime.UtcNow.Date;
            return today.ToUnixMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for the end of today (UTC)
        /// </summary>
        /// <returns>Unix milliseconds timestamp for end of today</returns>
        public static long EndOfToday()
        {
            var endOfDay = DateTime.UtcNow.Date.AddDays(1).AddMilliseconds(-1);
            return endOfDay.ToUnixMilliseconds();
        }
    }
}
