/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;

namespace AdGuard.ApiClient.Helpers
{
    /// <summary>
    /// Extension methods for DateTime conversions to Unix milliseconds (as used by AdGuard DNS API).
    /// </summary>
    /// <remarks>
    /// <para>
    /// The AdGuard DNS API uses Unix milliseconds timestamps for all date/time fields.
    /// This class provides convenient methods for converting between .NET DateTime/DateTimeOffset
    /// types and Unix milliseconds timestamps.
    /// </para>
    /// <para>
    /// All methods in this class work with UTC time to ensure consistency across time zones.
    /// Local DateTime values are automatically converted to UTC before processing.
    /// </para>
    /// </remarks>
    /// <example>
    /// Converting DateTime to Unix milliseconds:
    /// <code>
    /// var now = DateTime.UtcNow;
    /// long unixMs = now.ToUnixMilliseconds();
    /// </code>
    ///
    /// Getting timestamps for API queries:
    /// <code>
    /// // Query logs from the last 24 hours
    /// var from = DateTimeExtensions.HoursAgo(24);
    /// var to = DateTimeExtensions.Now();
    /// var logs = await api.GetQueryLogAsync(from, to);
    /// </code>
    /// </example>
    public static class DateTimeExtensions
    {
        /// <summary>
        /// The Unix epoch (January 1, 1970, 00:00:00 UTC).
        /// </summary>
        /// <remarks>
        /// This is the reference point for all Unix timestamp calculations.
        /// </remarks>
        private static readonly DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);

        /// <summary>
        /// Converts a DateTime to Unix milliseconds timestamp.
        /// </summary>
        /// <param name="dateTime">The DateTime to convert. Can be local or UTC time.</param>
        /// <returns>The Unix milliseconds timestamp representing the specified DateTime.</returns>
        /// <remarks>
        /// <para>If the DateTime is not in UTC, it will be converted to UTC before calculation.</para>
        /// <para>The result is always positive for dates after 1970-01-01 00:00:00 UTC.</para>
        /// </remarks>
        /// <example>
        /// <code>
        /// var dateTime = new DateTime(2024, 1, 15, 12, 30, 0, DateTimeKind.Utc);
        /// long unixMs = dateTime.ToUnixMilliseconds();
        /// // unixMs = 1705320600000
        /// </code>
        /// </example>
        public static long ToUnixMilliseconds(this DateTime dateTime)
        {
            var utcDateTime = dateTime.ToUniversalTime();
            return (long)(utcDateTime - UnixEpoch).TotalMilliseconds;
        }

        /// <summary>
        /// Converts a DateTimeOffset to Unix milliseconds timestamp.
        /// </summary>
        /// <param name="dateTimeOffset">The DateTimeOffset to convert.</param>
        /// <returns>The Unix milliseconds timestamp representing the specified DateTimeOffset.</returns>
        /// <remarks>
        /// DateTimeOffset values inherently include timezone information, so the conversion
        /// correctly accounts for the offset when calculating the UTC-based Unix timestamp.
        /// </remarks>
        /// <example>
        /// <code>
        /// var dto = new DateTimeOffset(2024, 1, 15, 12, 30, 0, TimeSpan.FromHours(-5));
        /// long unixMs = dto.ToUnixMilliseconds();
        /// </code>
        /// </example>
        public static long ToUnixMilliseconds(this DateTimeOffset dateTimeOffset)
        {
            return dateTimeOffset.ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Converts Unix milliseconds timestamp to DateTime (UTC).
        /// </summary>
        /// <param name="unixMilliseconds">The Unix milliseconds timestamp to convert.</param>
        /// <returns>A DateTime in UTC representing the specified timestamp.</returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown when the resulting DateTime would be outside the valid range for DateTime.
        /// </exception>
        /// <remarks>
        /// The returned DateTime always has <see cref="DateTimeKind.Utc"/> set.
        /// To convert to local time, use <c>.ToLocalTime()</c> on the result.
        /// </remarks>
        /// <example>
        /// <code>
        /// long unixMs = 1705320600000;
        /// DateTime dateTime = DateTimeExtensions.FromUnixMilliseconds(unixMs);
        /// // dateTime = 2024-01-15 12:30:00 UTC
        /// </code>
        /// </example>
        public static DateTime FromUnixMilliseconds(long unixMilliseconds)
        {
            return UnixEpoch.AddMilliseconds(unixMilliseconds);
        }

        /// <summary>
        /// Converts Unix milliseconds timestamp to DateTimeOffset (UTC).
        /// </summary>
        /// <param name="unixMilliseconds">The Unix milliseconds timestamp to convert.</param>
        /// <returns>A DateTimeOffset in UTC representing the specified timestamp.</returns>
        /// <exception cref="ArgumentOutOfRangeException">
        /// Thrown when the resulting DateTimeOffset would be outside the valid range.
        /// </exception>
        /// <remarks>
        /// The returned DateTimeOffset has an offset of TimeSpan.Zero (UTC).
        /// </remarks>
        /// <example>
        /// <code>
        /// long unixMs = 1705320600000;
        /// DateTimeOffset dto = DateTimeExtensions.FromUnixMillisecondsToOffset(unixMs);
        /// </code>
        /// </example>
        public static DateTimeOffset FromUnixMillisecondsToOffset(long unixMilliseconds)
        {
            return DateTimeOffset.FromUnixTimeMilliseconds(unixMilliseconds);
        }

        /// <summary>
        /// Gets Unix milliseconds for the current UTC time.
        /// </summary>
        /// <returns>The current Unix milliseconds timestamp.</returns>
        /// <remarks>
        /// This is equivalent to <c>DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()</c>
        /// but provides a more convenient syntax for API calls.
        /// </remarks>
        /// <example>
        /// <code>
        /// // Use as the 'to' parameter for a query
        /// var logs = await api.GetQueryLogAsync(DateTimeExtensions.HoursAgo(1), DateTimeExtensions.Now());
        /// </code>
        /// </example>
        public static long Now()
        {
            return DateTimeOffset.UtcNow.ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for a time relative to now.
        /// </summary>
        /// <param name="timeSpan">The TimeSpan to add to the current time. Can be positive (future) or negative (past).</param>
        /// <returns>The Unix milliseconds timestamp for the calculated time.</returns>
        /// <remarks>
        /// Positive TimeSpan values return timestamps in the future.
        /// Negative TimeSpan values return timestamps in the past.
        /// </remarks>
        /// <example>
        /// <code>
        /// // Get timestamp for 1 hour from now
        /// long futureTime = DateTimeExtensions.FromNow(TimeSpan.FromHours(1));
        ///
        /// // Get timestamp for 30 minutes ago
        /// long pastTime = DateTimeExtensions.FromNow(TimeSpan.FromMinutes(-30));
        /// </code>
        /// </example>
        public static long FromNow(TimeSpan timeSpan)
        {
            return DateTimeOffset.UtcNow.Add(timeSpan).ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for X days ago.
        /// </summary>
        /// <param name="days">Number of days ago. The value is automatically made positive.</param>
        /// <returns>The Unix milliseconds timestamp for the specified number of days ago.</returns>
        /// <remarks>
        /// The <paramref name="days"/> value is automatically converted to a positive number,
        /// so both <c>DaysAgo(7)</c> and <c>DaysAgo(-7)</c> return the timestamp for 7 days ago.
        /// </remarks>
        /// <example>
        /// <code>
        /// // Get statistics for the last 7 days
        /// var from = DateTimeExtensions.DaysAgo(7);
        /// var to = DateTimeExtensions.Now();
        /// var stats = await api.GetStatisticsAsync(from, to);
        /// </code>
        /// </example>
        public static long DaysAgo(int days)
        {
            return DateTimeOffset.UtcNow.AddDays(-Math.Abs(days)).ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for X hours ago.
        /// </summary>
        /// <param name="hours">Number of hours ago. The value is automatically made positive.</param>
        /// <returns>The Unix milliseconds timestamp for the specified number of hours ago.</returns>
        /// <remarks>
        /// The <paramref name="hours"/> value is automatically converted to a positive number,
        /// so both <c>HoursAgo(24)</c> and <c>HoursAgo(-24)</c> return the timestamp for 24 hours ago.
        /// </remarks>
        /// <example>
        /// <code>
        /// // Get query logs for the last hour
        /// var from = DateTimeExtensions.HoursAgo(1);
        /// var to = DateTimeExtensions.Now();
        /// var logs = await api.GetQueryLogAsync(from, to);
        /// </code>
        /// </example>
        public static long HoursAgo(int hours)
        {
            return DateTimeOffset.UtcNow.AddHours(-Math.Abs(hours)).ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for X minutes ago.
        /// </summary>
        /// <param name="minutes">Number of minutes ago. The value is automatically made positive.</param>
        /// <returns>The Unix milliseconds timestamp for the specified number of minutes ago.</returns>
        /// <remarks>
        /// The <paramref name="minutes"/> value is automatically converted to a positive number.
        /// </remarks>
        /// <example>
        /// <code>
        /// // Get query logs for the last 30 minutes
        /// var from = DateTimeExtensions.MinutesAgo(30);
        /// var logs = await api.GetQueryLogAsync(from, DateTimeExtensions.Now());
        /// </code>
        /// </example>
        public static long MinutesAgo(int minutes)
        {
            return DateTimeOffset.UtcNow.AddMinutes(-Math.Abs(minutes)).ToUnixTimeMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for the start of today (UTC).
        /// </summary>
        /// <returns>The Unix milliseconds timestamp for 00:00:00 UTC today.</returns>
        /// <remarks>
        /// This returns the timestamp for the start of the current UTC day,
        /// which may differ from the local day depending on timezone.
        /// </remarks>
        /// <example>
        /// <code>
        /// // Get all queries from today
        /// var from = DateTimeExtensions.StartOfToday();
        /// var to = DateTimeExtensions.Now();
        /// var logs = await api.GetQueryLogAsync(from, to);
        /// </code>
        /// </example>
        public static long StartOfToday()
        {
            var today = DateTime.UtcNow.Date;
            return today.ToUnixMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for the end of today (UTC).
        /// </summary>
        /// <returns>The Unix milliseconds timestamp for 23:59:59.999 UTC today.</returns>
        /// <remarks>
        /// This returns the timestamp for one millisecond before midnight UTC,
        /// effectively the last moment of the current UTC day.
        /// </remarks>
        /// <example>
        /// <code>
        /// // Set a scheduled task to run at end of day
        /// long endOfDay = DateTimeExtensions.EndOfToday();
        /// </code>
        /// </example>
        public static long EndOfToday()
        {
            var endOfDay = DateTime.UtcNow.Date.AddDays(1).AddMilliseconds(-1);
            return endOfDay.ToUnixMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for the start of a specific date (UTC).
        /// </summary>
        /// <param name="date">The date to get the start of. Time component is ignored.</param>
        /// <returns>The Unix milliseconds timestamp for 00:00:00 UTC on the specified date.</returns>
        /// <example>
        /// <code>
        /// // Get logs from the start of a specific date
        /// var date = new DateTime(2024, 1, 15);
        /// var from = DateTimeExtensions.StartOfDay(date);
        /// </code>
        /// </example>
        public static long StartOfDay(DateTime date)
        {
            return date.Date.ToUniversalTime().ToUnixMilliseconds();
        }

        /// <summary>
        /// Gets Unix milliseconds for the end of a specific date (UTC).
        /// </summary>
        /// <param name="date">The date to get the end of. Time component is ignored.</param>
        /// <returns>The Unix milliseconds timestamp for 23:59:59.999 UTC on the specified date.</returns>
        /// <example>
        /// <code>
        /// // Get logs until the end of a specific date
        /// var date = new DateTime(2024, 1, 15);
        /// var to = DateTimeExtensions.EndOfDay(date);
        /// </code>
        /// </example>
        public static long EndOfDay(DateTime date)
        {
            return date.Date.ToUniversalTime().AddDays(1).AddMilliseconds(-1).ToUnixMilliseconds();
        }

        /// <summary>
        /// Formats a Unix milliseconds timestamp as an ISO 8601 string.
        /// </summary>
        /// <param name="unixMilliseconds">The Unix milliseconds timestamp to format.</param>
        /// <returns>An ISO 8601 formatted date/time string (e.g., "2024-01-15T12:30:00.000Z").</returns>
        /// <example>
        /// <code>
        /// long timestamp = DateTimeExtensions.Now();
        /// string formatted = DateTimeExtensions.FormatAsIso8601(timestamp);
        /// // Output: "2024-01-15T12:30:00.000Z"
        /// </code>
        /// </example>
        public static string FormatAsIso8601(long unixMilliseconds)
        {
            return FromUnixMilliseconds(unixMilliseconds).ToString("yyyy-MM-ddTHH:mm:ss.fffZ");
        }

        /// <summary>
        /// Formats a Unix milliseconds timestamp as a human-readable string.
        /// </summary>
        /// <param name="unixMilliseconds">The Unix milliseconds timestamp to format.</param>
        /// <param name="format">Optional format string. Defaults to "yyyy-MM-dd HH:mm:ss".</param>
        /// <returns>A formatted date/time string.</returns>
        /// <example>
        /// <code>
        /// long timestamp = DateTimeExtensions.Now();
        /// string formatted = DateTimeExtensions.Format(timestamp, "dd/MM/yyyy HH:mm");
        /// // Output: "15/01/2024 12:30"
        /// </code>
        /// </example>
        public static string Format(long unixMilliseconds, string format = "yyyy-MM-dd HH:mm:ss")
        {
            return FromUnixMilliseconds(unixMilliseconds).ToString(format);
        }
    }
}
