/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Threading.Tasks;
using AdGuard.ApiClient.Client;
using Polly;
using Polly.Retry;

namespace AdGuard.ApiClient.Helpers
{
    /// <summary>
    /// Helper class for creating retry policies for API calls
    /// </summary>
    public static class RetryPolicyHelper
    {
        /// <summary>
        /// Creates a retry policy for handling rate limiting (429) and transient errors
        /// </summary>
        /// <param name="maxRetries">Maximum number of retries (default: 3)</param>
        /// <param name="initialDelay">Initial delay between retries in seconds (default: 2)</param>
        /// <returns>Async retry policy</returns>
        public static AsyncRetryPolicy CreateDefaultRetryPolicy(int maxRetries = 3, int initialDelay = 2)
        {
            return Policy
                .Handle<ApiException>(ex => IsRetryableException(ex))
                .WaitAndRetryAsync(
                    maxRetries,
                    retryAttempt => TimeSpan.FromSeconds(initialDelay * Math.Pow(2, retryAttempt - 1)),
                    onRetry: (exception, timeSpan, retryCount, context) =>
                    {
                        Console.WriteLine($"Retry {retryCount} after {timeSpan.TotalSeconds}s delay. Error: {exception.Message}");
                    }
                );
        }

        /// <summary>
        /// Creates a typed retry policy for handling rate limiting and transient errors
        /// </summary>
        /// <typeparam name="T">Return type of the API call</typeparam>
        /// <param name="maxRetries">Maximum number of retries (default: 3)</param>
        /// <param name="initialDelay">Initial delay between retries in seconds (default: 2)</param>
        /// <returns>Async retry policy</returns>
        public static AsyncRetryPolicy<T> CreateDefaultRetryPolicy<T>(int maxRetries = 3, int initialDelay = 2)
        {
            return Policy<T>
                .Handle<ApiException>(ex => IsRetryableException(ex))
                .WaitAndRetryAsync(
                    maxRetries,
                    retryAttempt => TimeSpan.FromSeconds(initialDelay * Math.Pow(2, retryAttempt - 1)),
                    onRetry: (result, timeSpan, retryCount, context) =>
                    {
                        if (result.Exception != null)
                        {
                            Console.WriteLine($"Retry {retryCount} after {timeSpan.TotalSeconds}s delay. Error: {result.Exception.Message}");
                        }
                    }
                );
        }

        /// <summary>
        /// Creates a retry policy specifically for rate limiting (429 errors)
        /// </summary>
        /// <param name="maxRetries">Maximum number of retries (default: 5)</param>
        /// <param name="baseDelay">Base delay between retries in seconds (default: 5)</param>
        /// <returns>Async retry policy</returns>
        public static AsyncRetryPolicy CreateRateLimitRetryPolicy(int maxRetries = 5, int baseDelay = 5)
        {
            return Policy
                .Handle<ApiException>(ex => ex.ErrorCode == 429)
                .WaitAndRetryAsync(
                    maxRetries,
                    retryAttempt => TimeSpan.FromSeconds(baseDelay * retryAttempt),
                    onRetry: (exception, timeSpan, retryCount, context) =>
                    {
                        Console.WriteLine($"Rate limit hit. Retry {retryCount}/{maxRetries} after {timeSpan.TotalSeconds}s");
                    }
                );
        }

        /// <summary>
        /// Executes an API call with the default retry policy
        /// </summary>
        /// <typeparam name="T">Return type of the API call</typeparam>
        /// <param name="apiCall">The API call function</param>
        /// <param name="maxRetries">Maximum number of retries (default: 3)</param>
        /// <returns>Result of the API call</returns>
        public static async Task<T> ExecuteWithRetryAsync<T>(Func<Task<T>> apiCall, int maxRetries = 3)
        {
            var policy = CreateDefaultRetryPolicy<T>(maxRetries);
            return await policy.ExecuteAsync(apiCall);
        }

        /// <summary>
        /// Executes an API call with the default retry policy
        /// </summary>
        /// <param name="apiCall">The API call function</param>
        /// <param name="maxRetries">Maximum number of retries (default: 3)</param>
        public static async Task ExecuteWithRetryAsync(Func<Task> apiCall, int maxRetries = 3)
        {
            var policy = CreateDefaultRetryPolicy(maxRetries);
            await policy.ExecuteAsync(apiCall);
        }

        /// <summary>
        /// Determines if an API exception should be retried
        /// </summary>
        /// <param name="exception">The API exception</param>
        /// <returns>True if the exception is retryable</returns>
        private static bool IsRetryableException(ApiException exception)
        {
            // Retry on rate limiting (429)
            if (exception.ErrorCode == 429)
                return true;

            // Retry on server errors (5xx)
            if (exception.ErrorCode >= 500 && exception.ErrorCode < 600)
                return true;

            // Retry on specific client errors that might be transient
            if (exception.ErrorCode == 408) // Request Timeout
                return true;

            return false;
        }
    }
}
