/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CategoryType : Category type
/// Category type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CategoryType {
    #[serde(rename = "ADS")]
    Ads,
    #[serde(rename = "TRACKERS")]
    Trackers,
    #[serde(rename = "SOCIAL_MEDIA")]
    SocialMedia,
    #[serde(rename = "CDN")]
    Cdn,
    #[serde(rename = "OTHERS")]
    Others,

}

impl std::fmt::Display for CategoryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ads => write!(f, "ADS"),
            Self::Trackers => write!(f, "TRACKERS"),
            Self::SocialMedia => write!(f, "SOCIAL_MEDIA"),
            Self::Cdn => write!(f, "CDN"),
            Self::Others => write!(f, "OTHERS"),
        }
    }
}

impl Default for CategoryType {
    fn default() -> CategoryType {
        Self::Ads
    }
}

