/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompanyQueriesStats : Company queries stats
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyQueriesStats {
    /// Company name
    #[serde(rename = "company_name")]
    pub company_name: String,
    #[serde(rename = "value")]
    pub value: Box<models::QueriesStats>,
}

impl CompanyQueriesStats {
    /// Company queries stats
    pub fn new(company_name: String, value: models::QueriesStats) -> CompanyQueriesStats {
        CompanyQueriesStats {
            company_name,
            value: Box::new(value),
        }
    }
}
