/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompanyDetailedQueriesStats : Company detailed queries stats
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyDetailedQueriesStats {
    /// Company name
    #[serde(rename = "company_name")]
    pub company_name: String,
    /// Domains count
    #[serde(rename = "domains_count")]
    pub domains_count: i32,
    /// Top domain by blocked queries
    #[serde(rename = "top_blocked_domain", skip_serializing_if = "Option::is_none")]
    pub top_blocked_domain: Option<String>,
    /// Top domain by queries
    #[serde(rename = "top_queries_domain")]
    pub top_queries_domain: String,
    #[serde(rename = "value")]
    pub value: Box<models::QueriesStats>,
}

impl CompanyDetailedQueriesStats {
    /// Company detailed queries stats
    pub fn new(company_name: String, domains_count: i32, top_queries_domain: String, value: models::QueriesStats) -> CompanyDetailedQueriesStats {
        CompanyDetailedQueriesStats {
            company_name,
            domains_count,
            top_blocked_domain: None,
            top_queries_domain,
            value: Box::new(value),
        }
    }
}

