/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompanyDetailedQueriesStatsList : Company detailed queries statistics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyDetailedQueriesStatsList {
    /// Pagination
    #[serde(rename = "pages")]
    pub pages: Vec<models::Page>,
    /// List of queries stats
    #[serde(rename = "stats")]
    pub stats: Vec<models::CompanyDetailedQueriesStats>,
}

impl CompanyDetailedQueriesStatsList {
    /// Company detailed queries statistics
    pub fn new(
        pages: Vec<models::Page>,
        stats: Vec<models::CompanyDetailedQueriesStats>,
    ) -> CompanyDetailedQueriesStatsList {
        CompanyDetailedQueriesStatsList { pages, stats }
    }
}
