/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConnectDeviceType : Connect Device Type
/// Connect Device Type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConnectDeviceType {
    #[serde(rename = "WINDOWS")]
    Windows,
    #[serde(rename = "ANDROID")]
    Android,
    #[serde(rename = "MAC")]
    Mac,
    #[serde(rename = "IOS")]
    Ios,
    #[serde(rename = "LINUX")]
    Linux,
    #[serde(rename = "ROUTER")]
    Router,
    #[serde(rename = "SMART_TV")]
    SmartTv,
    #[serde(rename = "GAME_CONSOLE")]
    GameConsole,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl std::fmt::Display for ConnectDeviceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Windows => write!(f, "WINDOWS"),
            Self::Android => write!(f, "ANDROID"),
            Self::Mac => write!(f, "MAC"),
            Self::Ios => write!(f, "IOS"),
            Self::Linux => write!(f, "LINUX"),
            Self::Router => write!(f, "ROUTER"),
            Self::SmartTv => write!(f, "SMART_TV"),
            Self::GameConsole => write!(f, "GAME_CONSOLE"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for ConnectDeviceType {
    fn default() -> ConnectDeviceType {
        Self::Windows
    }
}
