/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CountryQueriesStatsList : Countries queries statistics
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CountryQueriesStatsList {
    /// List of queries stats
    #[serde(rename = "stats")]
    pub stats: Vec<models::CountryQueriesStats>,
}

impl CountryQueriesStatsList {
    /// Countries queries statistics
    pub fn new(stats: Vec<models::CountryQueriesStats>) -> CountryQueriesStatsList {
        CountryQueriesStatsList {
            stats,
        }
    }
}

