/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeviceSettingsUpdate : Device settings update
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeviceSettingsUpdate {
    /// Use only DNS-over-HTTPS with authentication
    #[serde(rename = "detect_doh_auth_only", skip_serializing_if = "Option::is_none")]
    pub detect_doh_auth_only: Option<bool>,
    /// Enable protection
    #[serde(rename = "protection_enabled", skip_serializing_if = "Option::is_none")]
    pub protection_enabled: Option<bool>,
}

impl DeviceSettingsUpdate {
    /// Device settings update
    pub fn new() -> DeviceSettingsUpdate {
        DeviceSettingsUpdate {
            detect_doh_auth_only: None,
            protection_enabled: None,
        }
    }
}

