/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsServer : DNS server (aka profile)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsServer {
    /// Default
    #[serde(rename = "default")]
    pub default: bool,
    /// List of connected devices
    #[serde(rename = "device_ids")]
    pub device_ids: Vec<String>,
    /// DNS server ID
    #[serde(rename = "id")]
    pub id: String,
    /// Name
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "settings")]
    pub settings: Box<models::DnsServerSettings>,
}

impl DnsServer {
    /// DNS server (aka profile)
    pub fn new(
        default: bool,
        device_ids: Vec<String>,
        id: String,
        name: String,
        settings: models::DnsServerSettings,
    ) -> DnsServer {
        DnsServer {
            default,
            device_ids,
            id,
            name,
            settings: Box::new(settings),
        }
    }
}
