/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsAddresses : DNS connecting info
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsAddresses {
    /// AdGuard DNS-over-HTTPS url
    #[serde(rename = "adguard_dns_over_https_url")]
    pub adguard_dns_over_https_url: String,
    /// AdGuard DNS-over-HTTPS with authentication url
    #[serde(rename = "adguard_dns_over_https_with_auth_url", skip_serializing_if = "Option::is_none")]
    pub adguard_dns_over_https_with_auth_url: Option<String>,
    /// AdGuard DNS-over-QUIC url
    #[serde(rename = "adguard_dns_over_quic_url")]
    pub adguard_dns_over_quic_url: String,
    /// AdGuard DNS-over-TLS url
    #[serde(rename = "adguard_dns_over_tls_url")]
    pub adguard_dns_over_tls_url: String,
    /// AdGuard VPN DNS-over-HTTPS url
    #[serde(rename = "adguard_vpn_dns_over_https_url")]
    pub adguard_vpn_dns_over_https_url: String,
    /// AdGuard VPN DNS-over-HTTPS with authentication url
    #[serde(rename = "adguard_vpn_dns_over_https_with_auth_url", skip_serializing_if = "Option::is_none")]
    pub adguard_vpn_dns_over_https_with_auth_url: Option<String>,
    /// AdGuard VPN DNS-over-QUIC url
    #[serde(rename = "adguard_vpn_dns_over_quic_url")]
    pub adguard_vpn_dns_over_quic_url: String,
    /// AdGuard VPN DNS-over-TLS url
    #[serde(rename = "adguard_vpn_dns_over_tls_url")]
    pub adguard_vpn_dns_over_tls_url: String,
    /// DNS-over-HTTPS
    #[serde(rename = "dns_over_https_url")]
    pub dns_over_https_url: String,
    /// DNS-over-HTTPS with authentication
    #[serde(rename = "dns_over_https_with_auth_url", skip_serializing_if = "Option::is_none")]
    pub dns_over_https_with_auth_url: Option<String>,
    /// DNS-over-QUIC
    #[serde(rename = "dns_over_quic_url")]
    pub dns_over_quic_url: String,
    /// DNS-over-TLS
    #[serde(rename = "dns_over_tls_url")]
    pub dns_over_tls_url: String,
    /// IP addresses
    #[serde(rename = "ip_addresses", skip_serializing_if = "Option::is_none")]
    pub ip_addresses: Option<Vec<models::IpAddress>>,
}

impl DnsAddresses {
    /// DNS connecting info
    pub fn new(adguard_dns_over_https_url: String, adguard_dns_over_quic_url: String, adguard_dns_over_tls_url: String, adguard_vpn_dns_over_https_url: String, adguard_vpn_dns_over_quic_url: String, adguard_vpn_dns_over_tls_url: String, dns_over_https_url: String, dns_over_quic_url: String, dns_over_tls_url: String) -> DnsAddresses {
        DnsAddresses {
            adguard_dns_over_https_url,
            adguard_dns_over_https_with_auth_url: None,
            adguard_dns_over_quic_url,
            adguard_dns_over_tls_url,
            adguard_vpn_dns_over_https_url,
            adguard_vpn_dns_over_https_with_auth_url: None,
            adguard_vpn_dns_over_quic_url,
            adguard_vpn_dns_over_tls_url,
            dns_over_https_url,
            dns_over_https_with_auth_url: None,
            dns_over_quic_url,
            dns_over_tls_url,
            ip_addresses: None,
        }
    }
}

