/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsServerSettings : DNS server settings
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsServerSettings {
    #[serde(rename = "access_settings")]
    pub access_settings: Box<models::DnsServerAccessSettings>,
    /// Approval for auto-connecting devices through a specific link type
    #[serde(rename = "auto_connect_devices_enabled")]
    pub auto_connect_devices_enabled: bool,
    /// Block prefetch proxy in Google chrome
    #[serde(rename = "block_chrome_prefetch")]
    pub block_chrome_prefetch: bool,
    /// If Firefox Canary should be blocked
    #[serde(rename = "block_firefox_canary")]
    pub block_firefox_canary: bool,
    /// Is private relay should be blocked
    #[serde(rename = "block_private_relay")]
    pub block_private_relay: bool,
    /// TTL for blocked request
    #[serde(rename = "block_ttl_seconds")]
    pub block_ttl_seconds: i32,
    #[serde(rename = "blocking_mode_settings")]
    pub blocking_mode_settings: Box<models::BlockingModeSettings>,
    #[serde(rename = "filter_lists_settings")]
    pub filter_lists_settings: Box<models::FilterListsSettings>,
    /// Consent to log IP addresses of requests
    #[serde(rename = "ip_log_enabled")]
    pub ip_log_enabled: bool,
    #[serde(rename = "parental_control_settings")]
    pub parental_control_settings: Box<models::ParentalControlSettings>,
    /// Is protection enabled
    #[serde(rename = "protection_enabled")]
    pub protection_enabled: bool,
    #[serde(rename = "safebrowsing_settings")]
    pub safebrowsing_settings: Box<models::SafebrowsingSettings>,
    #[serde(rename = "user_rules_settings")]
    pub user_rules_settings: Box<models::UserRulesSettings>,
}

impl DnsServerSettings {
    /// DNS server settings
    pub fn new(access_settings: models::DnsServerAccessSettings, auto_connect_devices_enabled: bool, block_chrome_prefetch: bool, block_firefox_canary: bool, block_private_relay: bool, block_ttl_seconds: i32, blocking_mode_settings: models::BlockingModeSettings, filter_lists_settings: models::FilterListsSettings, ip_log_enabled: bool, parental_control_settings: models::ParentalControlSettings, protection_enabled: bool, safebrowsing_settings: models::SafebrowsingSettings, user_rules_settings: models::UserRulesSettings) -> DnsServerSettings {
        DnsServerSettings {
            access_settings: Box::new(access_settings),
            auto_connect_devices_enabled,
            block_chrome_prefetch,
            block_firefox_canary,
            block_private_relay,
            block_ttl_seconds,
            blocking_mode_settings: Box::new(blocking_mode_settings),
            filter_lists_settings: Box::new(filter_lists_settings),
            ip_log_enabled,
            parental_control_settings: Box::new(parental_control_settings),
            protection_enabled,
            safebrowsing_settings: Box::new(safebrowsing_settings),
            user_rules_settings: Box::new(user_rules_settings),
        }
    }
}

