/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsServerSettingsUpdate : DNS server settings update action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsServerSettingsUpdate {
    #[serde(rename = "access_settings", skip_serializing_if = "Option::is_none")]
    pub access_settings: Option<Box<models::DnsServerAccessSettingsUpdate>>,
    /// Approval for auto-connecting devices through a specific link type
    #[serde(rename = "auto_connect_devices_enabled", skip_serializing_if = "Option::is_none")]
    pub auto_connect_devices_enabled: Option<bool>,
    /// Block prefetch proxy in Google chrome
    #[serde(rename = "block_chrome_prefetch", skip_serializing_if = "Option::is_none")]
    pub block_chrome_prefetch: Option<bool>,
    /// If Firefox Canary should be blocked
    #[serde(rename = "block_firefox_canary", skip_serializing_if = "Option::is_none")]
    pub block_firefox_canary: Option<bool>,
    /// Is private relay should be blocked
    #[serde(rename = "block_private_relay", skip_serializing_if = "Option::is_none")]
    pub block_private_relay: Option<bool>,
    /// TTL for blocked request
    #[serde(rename = "block_ttl_seconds", skip_serializing_if = "Option::is_none")]
    pub block_ttl_seconds: Option<i32>,
    #[serde(rename = "blocking_mode_settings", skip_serializing_if = "Option::is_none")]
    pub blocking_mode_settings: Option<Box<models::BlockingModeSettingsUpdate>>,
    #[serde(rename = "filter_lists_settings", skip_serializing_if = "Option::is_none")]
    pub filter_lists_settings: Option<Box<models::FilterListsSettingsUpdate>>,
    /// Consent to log IP addresses of requests
    #[serde(rename = "ip_log_enabled", skip_serializing_if = "Option::is_none")]
    pub ip_log_enabled: Option<bool>,
    #[serde(rename = "parental_control_settings", skip_serializing_if = "Option::is_none")]
    pub parental_control_settings: Option<Box<models::ParentalControlSettingsUpdate>>,
    /// Is protection enabled
    #[serde(rename = "protection_enabled", skip_serializing_if = "Option::is_none")]
    pub protection_enabled: Option<bool>,
    #[serde(rename = "safebrowsing_settings", skip_serializing_if = "Option::is_none")]
    pub safebrowsing_settings: Option<Box<models::SafebrowsingSettingsUpdate>>,
    #[serde(rename = "user_rules_settings", skip_serializing_if = "Option::is_none")]
    pub user_rules_settings: Option<Box<models::UserRulesSettingsUpdate>>,
}

impl DnsServerSettingsUpdate {
    /// DNS server settings update action
    pub fn new() -> DnsServerSettingsUpdate {
        DnsServerSettingsUpdate {
            access_settings: None,
            auto_connect_devices_enabled: None,
            block_chrome_prefetch: None,
            block_firefox_canary: None,
            block_private_relay: None,
            block_ttl_seconds: None,
            blocking_mode_settings: None,
            filter_lists_settings: None,
            ip_log_enabled: None,
            parental_control_settings: None,
            protection_enabled: None,
            safebrowsing_settings: None,
            user_rules_settings: None,
        }
    }
}

