/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DnsProtoResponseType : DNS proto response type
/// DNS proto response type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DnsProtoResponseType {
    #[serde(rename = "RcodeSuccess")]
    RcodeSuccess,
    #[serde(rename = "RcodeFormatError")]
    RcodeFormatError,
    #[serde(rename = "RcodeServerFailure")]
    RcodeServerFailure,
    #[serde(rename = "RcodeNameError")]
    RcodeNameError,
    #[serde(rename = "RcodeNotImplemented")]
    RcodeNotImplemented,
    #[serde(rename = "RcodeRefused")]
    RcodeRefused,
    #[serde(rename = "RcodeYXDomain")]
    RcodeYxDomain,
    #[serde(rename = "RcodeYXRrset")]
    RcodeYxRrset,
    #[serde(rename = "RcodeNXRrset")]
    RcodeNxRrset,
    #[serde(rename = "RcodeNotAuth")]
    RcodeNotAuth,
    #[serde(rename = "RcodeNotZone")]
    RcodeNotZone,
    #[serde(rename = "RcodeBadSig")]
    RcodeBadSig,
    #[serde(rename = "RcodeBadVers")]
    RcodeBadVers,
    #[serde(rename = "RcodeBadKey")]
    RcodeBadKey,
    #[serde(rename = "RcodeBadTime")]
    RcodeBadTime,
    #[serde(rename = "RcodeBadMode")]
    RcodeBadMode,
    #[serde(rename = "RcodeBadName")]
    RcodeBadName,
    #[serde(rename = "RcodeBadAlg")]
    RcodeBadAlg,
    #[serde(rename = "RcodeBadTrunc")]
    RcodeBadTrunc,
    #[serde(rename = "RcodeBadCookie")]
    RcodeBadCookie,

}

impl std::fmt::Display for DnsProtoResponseType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::RcodeSuccess => write!(f, "RcodeSuccess"),
            Self::RcodeFormatError => write!(f, "RcodeFormatError"),
            Self::RcodeServerFailure => write!(f, "RcodeServerFailure"),
            Self::RcodeNameError => write!(f, "RcodeNameError"),
            Self::RcodeNotImplemented => write!(f, "RcodeNotImplemented"),
            Self::RcodeRefused => write!(f, "RcodeRefused"),
            Self::RcodeYxDomain => write!(f, "RcodeYXDomain"),
            Self::RcodeYxRrset => write!(f, "RcodeYXRrset"),
            Self::RcodeNxRrset => write!(f, "RcodeNXRrset"),
            Self::RcodeNotAuth => write!(f, "RcodeNotAuth"),
            Self::RcodeNotZone => write!(f, "RcodeNotZone"),
            Self::RcodeBadSig => write!(f, "RcodeBadSig"),
            Self::RcodeBadVers => write!(f, "RcodeBadVers"),
            Self::RcodeBadKey => write!(f, "RcodeBadKey"),
            Self::RcodeBadTime => write!(f, "RcodeBadTime"),
            Self::RcodeBadMode => write!(f, "RcodeBadMode"),
            Self::RcodeBadName => write!(f, "RcodeBadName"),
            Self::RcodeBadAlg => write!(f, "RcodeBadAlg"),
            Self::RcodeBadTrunc => write!(f, "RcodeBadTrunc"),
            Self::RcodeBadCookie => write!(f, "RcodeBadCookie"),
        }
    }
}

impl Default for DnsProtoResponseType {
    fn default() -> DnsProtoResponseType {
        Self::RcodeSuccess
    }
}

