/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : Error response
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    #[serde(rename = "error_code")]
    pub error_code: models::ErrorCodes,
    /// Fields errors
    #[serde(rename = "fields")]
    pub fields: Vec<models::FieldError>,
    /// Error message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ErrorResponse {
    /// Error response
    pub fn new(error_code: models::ErrorCodes, fields: Vec<models::FieldError>) -> ErrorResponse {
        ErrorResponse {
            error_code,
            fields,
            message: None,
        }
    }
}
