/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorCodes : Possible error codes
/// Possible error codes
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorCodes {
    #[serde(rename = "BAD_REQUEST")]
    BadRequest,
    #[serde(rename = "FIELD_REQUIRED")]
    FieldRequired,
    #[serde(rename = "FIELD_WRONG_VALUE")]
    FieldWrongValue,
    #[serde(rename = "FIELD_REACHED_LIMIT")]
    FieldReachedLimit,
    #[serde(rename = "UNKNOWN")]
    Unknown,
}

impl std::fmt::Display for ErrorCodes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BadRequest => write!(f, "BAD_REQUEST"),
            Self::FieldRequired => write!(f, "FIELD_REQUIRED"),
            Self::FieldWrongValue => write!(f, "FIELD_WRONG_VALUE"),
            Self::FieldReachedLimit => write!(f, "FIELD_REACHED_LIMIT"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for ErrorCodes {
    fn default() -> ErrorCodes {
        Self::BadRequest
    }
}
