/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilterListItem : Filter
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilterListItem {
    /// The flag that the filter is on or off
    #[serde(rename = "enabled")]
    pub enabled: bool,
    /// Filter identifier
    #[serde(rename = "filter_id")]
    pub filter_id: String,
}

impl FilterListItem {
    /// Filter
    pub fn new(enabled: bool, filter_id: String) -> FilterListItem {
        FilterListItem {
            enabled,
            filter_id,
        }
    }
}

