/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilteringActionStatus : Filtering action status
/// Filtering action status
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilteringActionStatus {
    #[serde(rename = "UNKNOWN")]
    Unknown,
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "REQUEST_BLOCKED")]
    RequestBlocked,
    #[serde(rename = "RESPONSE_BLOCKED")]
    ResponseBlocked,
    #[serde(rename = "REQUEST_ALLOWED")]
    RequestAllowed,
    #[serde(rename = "RESPONSE_ALLOWED")]
    ResponseAllowed,
    #[serde(rename = "MODIFIED")]
    Modified,
}

impl std::fmt::Display for FilteringActionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Unknown => write!(f, "UNKNOWN"),
            Self::None => write!(f, "NONE"),
            Self::RequestBlocked => write!(f, "REQUEST_BLOCKED"),
            Self::ResponseBlocked => write!(f, "RESPONSE_BLOCKED"),
            Self::RequestAllowed => write!(f, "REQUEST_ALLOWED"),
            Self::ResponseAllowed => write!(f, "RESPONSE_ALLOWED"),
            Self::Modified => write!(f, "MODIFIED"),
        }
    }
}

impl Default for FilteringActionStatus {
    fn default() -> FilteringActionStatus {
        Self::Unknown
    }
}
