/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilteringActionSource : Filtering action source
/// Filtering action source
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FilteringActionSource {
    #[serde(rename = "FILTERS")]
    Filters,
    #[serde(rename = "USER_FILTER")]
    UserFilter,
    #[serde(rename = "SAFEBROWSING")]
    Safebrowsing,
    #[serde(rename = "PARENTAL_SAFE_SEARCH")]
    ParentalSafeSearch,
    #[serde(rename = "PARENTAL_YOUTUBE")]
    ParentalYoutube,
    #[serde(rename = "PARENTAL_ADULT")]
    ParentalAdult,
    #[serde(rename = "PARENTAL_BLOCKED_SERVICE")]
    ParentalBlockedService,
    #[serde(rename = "PARENTAL_SCHEDULE")]
    ParentalSchedule,
    #[serde(rename = "NEWLY_REGISTERED_DOMAINS")]
    NewlyRegisteredDomains,

}

impl std::fmt::Display for FilteringActionSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Filters => write!(f, "FILTERS"),
            Self::UserFilter => write!(f, "USER_FILTER"),
            Self::Safebrowsing => write!(f, "SAFEBROWSING"),
            Self::ParentalSafeSearch => write!(f, "PARENTAL_SAFE_SEARCH"),
            Self::ParentalYoutube => write!(f, "PARENTAL_YOUTUBE"),
            Self::ParentalAdult => write!(f, "PARENTAL_ADULT"),
            Self::ParentalBlockedService => write!(f, "PARENTAL_BLOCKED_SERVICE"),
            Self::ParentalSchedule => write!(f, "PARENTAL_SCHEDULE"),
            Self::NewlyRegisteredDomains => write!(f, "NEWLY_REGISTERED_DOMAINS"),
        }
    }
}

impl Default for FilteringActionSource {
    fn default() -> FilteringActionSource {
        Self::Filters
    }
}

