/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FilteringInfo : Filtering info
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FilteringInfo {
    /// Web service ID
    #[serde(rename = "blocked_service_id", skip_serializing_if = "Option::is_none")]
    pub blocked_service_id: Option<String>,
    /// Filter ID
    #[serde(rename = "filter_id", skip_serializing_if = "Option::is_none")]
    pub filter_id: Option<String>,
    /// Filter rule
    #[serde(rename = "filter_rule", skip_serializing_if = "Option::is_none")]
    pub filter_rule: Option<String>,
    #[serde(rename = "filtering_status", skip_serializing_if = "Option::is_none")]
    pub filtering_status: Option<models::FilteringActionStatus>,
    #[serde(rename = "filtering_type", skip_serializing_if = "Option::is_none")]
    pub filtering_type: Option<models::FilteringActionSource>,
}

impl FilteringInfo {
    /// Filtering info
    pub fn new() -> FilteringInfo {
        FilteringInfo {
            blocked_service_id: None,
            filter_id: None,
            filter_rule: None,
            filtering_status: None,
            filtering_type: None,
        }
    }
}
