/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IpType : IP address type
/// IP address type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IpType {
    #[serde(rename = "V4")]
    V4,
    #[serde(rename = "V6")]
    V6,

}

impl std::fmt::Display for IpType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::V4 => write!(f, "V4"),
            Self::V6 => write!(f, "V6"),
        }
    }
}

impl Default for IpType {
    fn default() -> IpType {
        Self::V4
    }
}

