/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LinkDedicatedIpv4 : Link dedicated IPv4 address to device
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LinkDedicatedIpv4 {
    /// Dedicated IPv4
    #[serde(rename = "ip")]
    pub ip: String,
}

impl LinkDedicatedIpv4 {
    /// Link dedicated IPv4 address to device
    pub fn new(ip: String) -> LinkDedicatedIpv4 {
        LinkDedicatedIpv4 { ip }
    }
}
