/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Page : Pagination
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Page {
    /// Is current page
    #[serde(rename = "current")]
    pub current: bool,
    /// Pagination cursor
    #[serde(rename = "page_cursor")]
    pub page_cursor: String,
    /// Page number
    #[serde(rename = "page_number")]
    pub page_number: i32,
}

impl Page {
    /// Pagination
    pub fn new(current: bool, page_cursor: String, page_number: i32) -> Page {
        Page {
            current,
            page_cursor,
            page_number,
        }
    }
}
