/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParentalControlSettingsUpdate : Parental control settings update action
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParentalControlSettingsUpdate {
    /// Disable porno content
    #[serde(rename = "block_adult_websites_enabled", skip_serializing_if = "Option::is_none")]
    pub block_adult_websites_enabled: Option<bool>,
    /// List of services with restricted access
    #[serde(rename = "blocked_services", skip_serializing_if = "Option::is_none")]
    pub blocked_services: Option<Vec<models::BlockedWebServiceUpdate>>,
    /// Is parental control enabled or not
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Enforces safe search for some search engines
    #[serde(rename = "engines_safe_search_enabled", skip_serializing_if = "Option::is_none")]
    pub engines_safe_search_enabled: Option<bool>,
    #[serde(rename = "screen_time_schedule", skip_serializing_if = "Option::is_none")]
    pub screen_time_schedule: Option<Box<models::ScheduleWeekUpdate>>,
    /// Enforces safe search on YouTube
    #[serde(rename = "youtube_safe_search_enabled", skip_serializing_if = "Option::is_none")]
    pub youtube_safe_search_enabled: Option<bool>,
}

impl ParentalControlSettingsUpdate {
    /// Parental control settings update action
    pub fn new() -> ParentalControlSettingsUpdate {
        ParentalControlSettingsUpdate {
            block_adult_websites_enabled: None,
            blocked_services: None,
            enabled: None,
            engines_safe_search_enabled: None,
            screen_time_schedule: None,
            youtube_safe_search_enabled: None,
        }
    }
}

