/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// QueriesStats : Overall / blocked / companies queries count
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueriesStats {
    /// Blocked queries count
    #[serde(rename = "blocked")]
    pub blocked: i64,
    /// Companies count
    #[serde(rename = "companies")]
    pub companies: i32,
    /// Overall queries count
    #[serde(rename = "queries")]
    pub queries: i64,
}

impl QueriesStats {
    /// Overall / blocked / companies queries count
    pub fn new(blocked: i64, companies: i32, queries: i64) -> QueriesStats {
        QueriesStats {
            blocked,
            companies,
            queries,
        }
    }
}
