/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RegularDnsProtoType : Regular DNS proto type. Scheduled for removal: PLAIN_TCP, PLAIN_UDP
/// Regular DNS proto type. Scheduled for removal: PLAIN_TCP, PLAIN_UDP
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RegularDnsProtoType {
    #[serde(rename = "DNS")]
    Dns,
    #[serde(rename = "PLAIN_TCP")]
    PlainTcp,
    #[serde(rename = "PLAIN_UDP")]
    PlainUdp,
}

impl std::fmt::Display for RegularDnsProtoType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Dns => write!(f, "DNS"),
            Self::PlainTcp => write!(f, "PLAIN_TCP"),
            Self::PlainUdp => write!(f, "PLAIN_UDP"),
        }
    }
}

impl Default for RegularDnsProtoType {
    fn default() -> RegularDnsProtoType {
        Self::Dns
    }
}
