/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ScheduleDay : Describes a schedule for day
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScheduleDay {
    #[serde(rename = "day_of_week")]
    pub day_of_week: models::DayOfWeek,
    /// Shows enabled/disabled day
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "from_time")]
    pub from_time: Box<models::ScheduleTime>,
    #[serde(rename = "to_time")]
    pub to_time: Box<models::ScheduleTime>,
}

impl ScheduleDay {
    /// Describes a schedule for day
    pub fn new(day_of_week: models::DayOfWeek, enabled: bool, from_time: models::ScheduleTime, to_time: models::ScheduleTime) -> ScheduleDay {
        ScheduleDay {
            day_of_week,
            enabled,
            from_time: Box::new(from_time),
            to_time: Box::new(to_time),
        }
    }
}

