/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SecureDnsProtoType : Secure DNS proto type. Scheduled for removal: DNSCRYPT_TCP, DNSCRYPT_UDP
/// Secure DNS proto type. Scheduled for removal: DNSCRYPT_TCP, DNSCRYPT_UDP
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SecureDnsProtoType {
    #[serde(rename = "DOH")]
    Doh,
    #[serde(rename = "DOQ")]
    Doq,
    #[serde(rename = "DOT")]
    Dot,
    #[serde(rename = "DNSCRYPT")]
    Dnscrypt,
    #[serde(rename = "DNSCRYPT_TCP")]
    DnscryptTcp,
    #[serde(rename = "DNSCRYPT_UDP")]
    DnscryptUdp,

}

impl std::fmt::Display for SecureDnsProtoType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Doh => write!(f, "DOH"),
            Self::Doq => write!(f, "DOQ"),
            Self::Dot => write!(f, "DOT"),
            Self::Dnscrypt => write!(f, "DNSCRYPT"),
            Self::DnscryptTcp => write!(f, "DNSCRYPT_TCP"),
            Self::DnscryptUdp => write!(f, "DNSCRYPT_UDP"),
        }
    }
}

impl Default for SecureDnsProtoType {
    fn default() -> SecureDnsProtoType {
        Self::Doh
    }
}

