/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TimeQueriesStats : Time moment query stats
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeQueriesStats {
    /// Time in millis
    #[serde(rename = "time_millis")]
    pub time_millis: i64,
    #[serde(rename = "value")]
    pub value: Box<models::QueriesStats>,
}

impl TimeQueriesStats {
    /// Time moment query stats
    pub fn new(time_millis: i64, value: models::QueriesStats) -> TimeQueriesStats {
        TimeQueriesStats {
            time_millis,
            value: Box::new(value),
        }
    }
}

