/*
 * AdGuard DNS API
 *
 * DNS API documentation
 *
 * The version of the OpenAPI document: 1.11
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebService : Web-service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebService {
    /// SVG icon
    #[serde(rename = "icon_svg")]
    pub icon_svg: String,
    /// Web-service identifier
    #[serde(rename = "id")]
    pub id: String,
    /// Web-service name
    #[serde(rename = "name")]
    pub name: String,
}

impl WebService {
    /// Web-service
    pub fn new(icon_svg: String, id: String, name: String) -> WebService {
        WebService {
            icon_svg,
            id,
            name,
        }
    }
}

